### ISSUE TITLE
Reduce number of client.Update in Reconcile

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#100]
**Is your feature request related to a problem? Please describe.**
The `Reconcile()` function is triggered 7 times when a new `RabbitmqCluster` is created. Depending on what parts of the CR are updated, we might trigger from 7 (e.g. update CR labels) to 2 (e.g. Service type in CR spec) reconcile loops. The reconcile function should produce the same output every time, however it seems unnecessary to trigger this function this often.

**Describe the solution you'd like**
Reduce the number of times `Reconcile()` is triggered. Ideally, just once per update to the CR, or just once for an update to a child resource. Ideally, updates from `Reconcile()` to child resources should not trigger additional reconcile loops.

The ideal situation might not be possible or very hard to achieve. We can improve slightly the number of times we call `client.Update()` to reduce the "pressure" from our controller to KubeAPI. The first place I have in mind is here: https://github.com/pivotal/rabbitmq-for-kubernetes/blob/d3eb92222d19281960ab07e7d57cf826768f6d5e/controllers/rabbitmqcluster_controller.go#L118-L127

The requeue in line 122 is not required. The function `client.Update()` mutates the object with the response returned from KubeAPI.

The function `addFinalizerIfNeeded()` also calls `client.Update()`. Could we add the finalizer as part of `MergeDefaults()` ?
We would have to modify slightly the condition in line 118, but it should be possible.

Feel free to suggest or refactor other parts of the `Reconcile()` to further reduce the number of calls to `client.Update()`.

**Describe alternatives you've considered**
N/A

**Comment by coro** [comment]
Stale issue, closing.
