### ISSUE TITLE
manage rabbitmq version with operator

### ISSUE THREAD

**Issue by steinarox** [rabbitmq/cluster-operator#1003]
**Is your feature request related to a problem? Please describe.**
To simplify rabbitmq management for simple usecases, it would be nice it rabbitmq-operator could take control over the versions deployed.

This code: https://github.com/rabbitmq/cluster-operator/blob/b853bb66bf36bc49c7872c365c1e642dfb9e565b/controllers/rabbitmqcluster_controller.go#L120
Skips setting the image version if already set.  

**Describe the solution you'd like**
A feature flag that will leave the image versions for connected rabbitmq clusters up to the operator. It will be the admins resposibility that the new default version can work without any migration. 
Maybe a feature flag like `CONTROL_RABBITMQ_IMAGE=true`, false is default

It should not override any rabbit ocontrols like the `pauseReconciliation`annotation. 

**Additional context**
This will simplify operation for smaller/simpler deployments and demos. running operator v.1.12.1

**Comment by mkuratczyk** [comment]
Do you mean the Operator would update the `image` value to automatically upgrade RabbitMQ? If you just want your instance to be always using the latest version, you can use an image tag that isn't too specific, for example there is `rabbitmq:3.9`. Add an `imagePullPolicy: Always` (through overrides) and you will always deploy the most recent 3.9.

**Comment by Zerpet** [comment]
The challenge here is that Cluster Operator does not monitor new versions of RabbitMQ i.e. it does not poll the registry in `image`. This proposal sounds specific to Cluster Operator upgrades (as in it should also upgrade all rabbits). 

You can achieve something similar if you don't specify an `image` in your manifest e.g.

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: custom-configuration
spec:
  replicas: 1
```

Everytime you apply this manifest, Kubernetes receives empty values for the properties you have not specified, therefore entering the conditional you quoted. Since we set a patch version of the image, it will apply the new default that comes with the Cluster Operator's specific version.

**Comment by steinarox** [comment]
@mkuratczyk if you can manually restart/rollout the statefulset that will work, but i would like to avoid manual cluster operations.

@Zerpet  the code that i linked to should work the way you describe. We are not adding image field in our definitions, however the image field gets patched into the definitions so in practice this does not work at the moment. If the intent is to work as you say, it seems like there is a bug in the controller somewhere else that persists the image property even if it should not.

**Comment by ChunyiLyu** [comment]
@steinarox The code you've linked to regarding [the default image](https://github.com/rabbitmq/cluster-operator/blob/b853bb66bf36bc49c7872c365c1e642dfb9e565b/controllers/rabbitmqcluster_controller.go#L120-L131), set image to the operator default if it's not set at the time of reconciliation, then it updates the actual definition of the rabbitmqcluster by `r.Update(ctx, rabbitmqCluster)`. So after this update, the rabbitmqcluster will have `spec.image` set in their manifest and even if your operator default image has been changed, it won't update existing rabbitmqcluster's image value.
