### ISSUE TITLE
Add Alerts for DiskLimit and MemoryLimit reached

### ISSUE THREAD

**Issue by edbyford** [rabbitmq/cluster-operator#1006]
@ansd commented on [Wed May 19 2021](https://github.com/rabbitmq/service-operator-experience/issues/34)

We currently have an alert for [LowDiskWatermarkPredicted](https://github.com/rabbitmq/cluster-operator/blob/main/observability/prometheus/rules/rabbitmq/low-disk-watermark-predicted.yml).

Let's add two more alerts:
1. Low Disk Watermark reached:
`rabbitmq_disk_space_available_bytes < 0` for more than 10 minutes
2. Memory limit reached: e.g. `rabbitmq_resident_memory_limit_bytes - rabbitmq_process_resident_memory_bytes < 0` for more than 10m

**Comment by ablease** [comment]
Hi @ansd. Similar to #33 Should we still play this story? We have some questions:

What is the intention with this story
Giving the age of this request, is it still relavent?
