### ISSUE TITLE
Vault default user example stuck at init container 

### ISSUE THREAD

**Issue by VVivid** [rabbitmq/cluster-operator#1025]
## Describe the bug
Rabbitmq cluster stuck at init container 

## To Reproduce
1. Go to  https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/vault-default-user#usage
2. Follow the usage and run setup.sh 
3. Apply rabbitmq.yaml

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**
Getting end-to-end how RabbitMQ integrates with Vault. 

## Screenshots
![Screen Shot 2022-04-27 at 4 41 37 PM](https://user-images.githubusercontent.com/60072429/165490328-619c8bab-155f-4811-917c-7e5cc8f9286e.png)

## Version and environment information
- Kubernetes: 1.21
 
## Additional context
I have created a pull request: https://github.com/rabbitmq/cluster-operator/pull/1024

**Comment by ChunyiLyu** [comment]
[Changing the default value for `RABBITMQ_NAMESPACE`](https://github.com/rabbitmq/cluster-operator/pull/1024) won't help other users who are not deploying `rabbitmq.yaml` while targeting the `default` namespace. 

I could update the example README to mention that [the namespace environment variable](https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/vault-default-user/setup.sh#L5) default to `examples` but can be set to a different value if you need to. What do you think?

**Comment by ChunyiLyu** [comment]
@VVivid Not everyone uses default namespace to try out examples. I don't know what's a "popular namespace" that people use in testing and I don't even know if there is one popular namespace.+ The environment variable `RABBITMQ_NAMESPACE` in the setup.sh script is configurable for this particular reason.
