### ISSUE TITLE
Release 1.12.1 went away

### ISSUE THREAD

**Issue by xvzf** [rabbitmq/cluster-operator#1038]
## Describe the bug
The release we have been using in our kustomization just went away (https://github.com/rabbitmq/cluster-operator/releases/download/v1.12.1/cluster-operator-quay-io.yml), is this intended and an actual description on why?
The tag is still there.

**Comment by ChunyiLyu** [comment]
Deleted by mistake. It's back: https://github.com/rabbitmq/cluster-operator/releases/tag/v1.12.1

**Comment by mstoetzer** [comment]
https://github.com/rabbitmq/cluster-operator/releases/download/v1.12.1/cluster-operator-quay-io.yml and https://github.com/rabbitmq/cluster-operator/releases/download/v1.12.1/cluster-operator.yml is still missing

**Comment by ChunyiLyu** [comment]
@mstoetzer Sorry about that. Could you check now?

**Comment by ChunyiLyu** [comment]
@mstoetzer Great! Thanks for using Cluster Operator 😀
