### ISSUE TITLE
Rabbitmq managment

### ISSUE THREAD

**Issue by schiavh** [rabbitmq/cluster-operator#1063]
## Describe the bug
The rabbitmq managment does not succeed to load overview and other interface options.

## To Reproduce
```
// install rabbitmq operator
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"

// install rabbitmq cluster
kubectl apply -f rabbit.yml
```
rabbit.yml:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbit
```

## Screenshots
![image](https://user-images.githubusercontent.com/5795865/173035639-ecccbd75-5232-44cb-bd0c-d0cbec8f6f8e.png)

## Version and environment information
- RabbitMQ: latest
- RabbitMQ Cluster Operator: latest
- Kubernetes: v1.23.6
- Cloud provider or hardware configuration: Cloud provider

**Comment by Zerpet** [comment]
I can't reproduce this issue with the steps you provided. I'm using Firefox 101.0. How are you accessing the management UI? Using a load balancer?

**Comment by Zerpet** [comment]
Feel free to reopen this issue if you find additional information
