### ISSUE TITLE
How to become your member?

### ISSUE THREAD

**Issue by jiuker** [rabbitmq/cluster-operator#1070]
Whether I have the honor to be your member？
What is the way? I didn't see the relevant instructions in this repo.
I have pr list:
[#1061](https://github.com/rabbitmq/cluster-operator/pull/1061) wrap all error
[#1040](https://github.com/rabbitmq/cluster-operator/pull/1040) change switch case
[#1009](https://github.com/rabbitmq/cluster-operator/pull/1009) change get config way
[#1076](https://github.com/rabbitmq/cluster-operator/pull/1076) fix imagepullserect bugs

**Comment by edbyford** [comment]
Thank you for your contributions! We will review the PRs and will provide comments there.

**Comment by jiuker** [comment]
> Thank you for your contributions! We will review the PRs and will provide comments there

[#1076](https://github.com/rabbitmq/cluster-operator/pull/1076) is new PR,please review.@[edbyford](https://github.com/edbyford)
