### ISSUE TITLE
Installation: error: the path "./prometheus/monitors/" does not exist

### ISSUE THREAD

**Issue by dmitrynovik** [rabbitmq/cluster-operator#1072]
## Describe the bug
Running the `quickstart.sh` fails: Installation: error: the path "./prometheus/monitors/" does not exist

## To Reproduce
1. In `quickstart.sh`, set the KUBE_PROMETHEUS_STACK_VERSION='36.0.2'
2. Run the  `quickstart.sh`

**Comment by MirahImage** [comment]
Thanks. For additional context, version `15.2.1` referenced in the script is not compatible with current Kubernetes versions

**Comment by MirahImage** [comment]
In the latest cluster operator 1.14.0 release, the kube prometheus version listed in `quickstart.sh`is `31.0.2`. This version is compatible with kubernetes 1.19.0+ and does not fail with this error. Please check out the repository at the latest release to ensure a consistent experience.

**Comment by dmitrynovik** [comment]
Hi @MirahImage, the same error happens with https://raw.githubusercontent.com/rabbitmq/cluster-operator/v1.14.0/observability/quickstart.sh:
`error: the path ".../prometheus/monitors/" does not exist`
