### ISSUE TITLE
The kubernetes cluster with three nodes updates the host configuration node by node. How to ensure that messages are not lost.

### ISSUE THREAD

**Issue by sjkcdpc** [rabbitmq/cluster-operator#1078]
# mq.yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: mq
spec:
  replicas: 3
  image: rabbitmq:3.8.7-management
  rabbitmq:
    additionalConfig: |
      default_user=admin
      default_pass=admin
    additionalPlugins:
    - rabbitmq_management
    - rabbitmq_management_agent
    - rabbitmq_web_dispatch
    - rabbitmq_federation
    - rabbitmq_federation_management
    - rabbitmq_shovel_management
    - rabbitmq_shovel
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence
              namespace: default
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
              volumeMode: Filesystem

**Comment by Zerpet** [comment]
I'm not sure I understand the issue or the question raised. 

Can you please describe in details what is happening? 
What issue are you observing with RabbitMQ?

**Comment by sjkcdpc** [comment]
Rabbitmq is deployed on the kubernetes cluster with three nodes. The configuration is as above.

Now we need to change the three machines from Intel to AMD. In this process, we worry about rabbitmq data loss. How can we ensure 100% data security?

**Comment by Zerpet** [comment]
The first recommendation is to upgrade RabbitMQ to a more recent patch. RabbitMQ 3.8.7 is not supported by the Operator, see here: https://github.com/rabbitmq/cluster-operator#supported-versions

Make sure you are using [Quorum Queues](https://rabbitmq.com/quorum-queues.html) and read through the reliability guide: https://rabbitmq.com/reliability.html
