### ISSUE TITLE
Full AMQP url inside generated secret

### ISSUE THREAD

**Issue by penumbra23** [rabbitmq/cluster-operator#1089]
Hi!

First of, thanks for the awesome work here, lots of problems solved with managing RabbitMQ myself.

In most charts/operators (i.e. Crunchy Postgres or Bitnami Cassandra) when generating a secret for the connection to the resource, besides separate config entries (username, password, host, port, ...) there's also the full URI to the resource, encapsulating the authentication and server domain part. The current secret has each of the specific entry as separate secret entries, so it would be neat to have the full AMQP URL also, in cases where libraries (notably, in my project it's `amqp-ts`) expect it.

I've already added it to my fork, added also unit tests, tomorrow I'm testing it on our dev cluster. So I'll open a PR with the additions.

Cheers!

**Comment by ablease** [comment]
Closing this, see https://github.com/rabbitmq/cluster-operator/pull/1090
