### ISSUE TITLE
Quickstart SVG is broken on firefox

### ISSUE THREAD

**Issue by mahmoudhossam** [rabbitmq/cluster-operator#1096]
## Describe the bug
The quickstart SVG in the readme doesn't render correctly on firefox.

**Expected behavior**
SVG should render correctly showing the steps 

## Screenshots

[Screencast from 07-13-2022 02:33:54 PM.webm](https://user-images.githubusercontent.com/619795/178735061-4e112b93-594a-40ad-99a1-e207d6267cc3.webm)

## Version and environment information
Firefox 102.0.1 (64-bit) on Arch Linux

**Comment by mkuratczyk** [comment]
Thanks for reporting the problem. However, it renders correctly for me (Firefox 102.0.1, macOS). Therefore, unless you can provide details of how the file is not a valid SVG file, I'd consider this a Firefox issue (or something else specific to your system).
