### ISSUE TITLE
Developers facing status conditions design document

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#115]
**Is your feature request related to a problem? Please describe.**
A design document to clearly lay out the reasoning behind the status condition design, and how to use the information from status conditions.

Design docs can be added under `docs/design`

**Additional context**
- status condition [google document](https://docs.google.com/document/d/1LrhcVQM7-8vkwUZv9VknRvilHBHlW-iX-D53KEgVKCg/edit#heading=h.ccefwrsoov11) (not public) ; some information might be out of date, make sure to check the current implementation.
- [rook/ceph design docs](https://github.com/rook/rook/tree/198df474512f5bfb0ec6bdba2bb8c891cc27b80d/design/ceph)
- [rook/cassandra design docs](https://github.com/rook/rook/tree/198df474512f5bfb0ec6bdba2bb8c891cc27b80d/design/cassandra)
- [coreos/etcd-operator design docs](https://github.com/coreos/etcd-operator/tree/master/doc/design)

**Comment by ansd** [comment]
In today's sync meeting we decided to close this issue.
