### ISSUE TITLE
Use apps/v1 type for StatefulSetSpec in RabbitmqCluster override

### ISSUE THREAD

**Issue by coro** [rabbitmq/cluster-operator#1152]
**Is your feature request related to a problem? Please describe.**
Currently, if a new field is exposed in the [StatefulSetSpec](https://pkg.go.dev/k8s.io/api/apps/v1#StatefulSetSpec) by the upstream Kubernetes API, it is not usable in the StatefulSet Override feature of the cluster-operator until it is manually added to the rabbitmq.com/v1beta1 API.

This is because the API in this operator [defines its own StatefulSetSpec](https://github.com/rabbitmq/cluster-operator/blob/5bbbbd2ef29b192e1981ac2c782413445d9e3231/api/v1beta1/rabbitmqcluster_types.go#L181-L236), which is a subset of the fields available in the upstream StatefulSetSpec.

I would like to be able to use the new v1.25 StatefulSet feature [Minimum ready seconds](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#minimum-ready-seconds) in the operator, but as it requires it to be specifically added to the subset StatefulSetSpec structure, I cannot currently.

**Describe the solution you'd like**
I would like for everything in [apps/v1.StatefulSetSpec](https://pkg.go.dev/k8s.io/api/apps/v1#StatefulSetSpec) to be able to be provided in `rabbitmqCluster.spec.override.statefulSet.spec`.

**Describe alternatives you've considered**
We could add just this field, but we would be left with the long-term complexity of maintaining this separate list of fields, and the context behind why not all fields are passable.

**Additional context**
There was originally a bug in kubebuilder that forced us to create our own EmbeddedObjectMeta. See @ChunyiLyu's comment in the Context of this PR: https://github.com/rabbitmq/cluster-operator/pull/175

[The fix](https://github.com/kubernetes-sigs/controller-tools/pull/557) is now in, meaning we should be able to use the core API types as requested above, making sure that we add the flag `generateEmbeddedObjectMeta=true` to controller-gen.

Converting a type in our API may require the use of a conversion webhook and a new API version.

**Comment by DanielePalaia** [comment]
As we understood that there is currently no way to implement this without having a breaking change on the operator I will move this one to Icebox at the moment and I've created: https://app.zenhub.com/workspaces/service-operator-experience-623895d9b17eb7001156689f/issues/rabbitmq/service-operator-experience/143 for the new parameter necessary
