### ISSUE TITLE
Add prometheus annotations to Pod Template by default

### ISSUE THREAD

**Issue by j4mcs** [rabbitmq/cluster-operator#118]
**Is your feature request related to a problem? Please describe.**
We removed the prometheus port from the ingress service in #83. Users can no longer add the prometheus annotation to the service in the CR to scrape the cluster metrics.

**Describe the solution you'd like**
 Scraping is possible by adding the prometheus annotations to the Pod Template:

```
annotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "15692"
```

Enabling this by default will mean the cluster won't have to be restarted to scrape metrics (without using a Pod Monitor)

**Describe alternatives you've considered**
It's possible to scrape all nodes in a cluster by adding the annotations to the headless service if the prometheus pod is exposed. There is no clear benefit (and added work) over the proposed method.

**Additional context**

**Comment by ChunyiLyu** [comment]
It's already done 🎉

**Comment by govindkailas** [comment]
Nevermind, figured out from here https://github.com/rabbitmq/cluster-operator/issues/961
