### ISSUE TITLE
Deploy rabbtimq cluster with cluster operator

### ISSUE THREAD

**Issue by janiu-001** [rabbitmq/cluster-operator#1193]
Dear expert,

I deployed the rabbitmq cluster with cluster operator and enabling rabbitmq_mqtt plugin on my pc, and it could work with rabbitmq:3.7-management. But i get the following error with rabbitmq:3.9-management and rabbitmq:3.11-management

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/19970581/202316871-90ec9c97-b8ce-4114-8db1-f79ac8eb0ce6.png">
And from the log, the mqtt plugin is enabled and listen on 1883:
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/19970581/202319881-e5aa9faf-da73-4743-889c-52ea0e79cd86.png">

And following is my yaml file:
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/19970581/202316985-8c367312-3453-46f3-b600-a7791131dfe6.png">

Very appreciate for your response!

**Comment by MirahImage** [comment]
Have you also added the additional container-port? See the example for [opening additional ports](https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/additionalPorts). 

As an aside, the operator automatically opens the default port for a service when that service is enabled, so for example, [if the mqtt plugin is enabled, the operator will by default open the associated port](https://github.com/rabbitmq/cluster-operator/blob/b9b0a6709ce9023f557e8e14662157559f5e6e52/internal/resource/service.go#L135), so you shouldn't need to use the override for this case.

**Comment by Zerpet** [comment]
You don't need the service override, the Operator will open the port for you in the generated service, if it sees `rabbitmq_mqtt` in additional plugins. If you remove the service override, this should work.

**Comment by janiu-001** [comment]
@Zerpet @MirahImage Thanks for your response! 
It did not work after removing the service override
<img width="829" alt="image" src="https://user-images.githubusercontent.com/19970581/202422591-aa7f260b-4b68-4fe1-b32f-0c2270dc2023.png">

It did not work either by adding the container port
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19970581/202423035-543b4d77-11bf-4151-9c97-d162444a6b9b.png">

From the log, the service already listen on the port 1883
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/19970581/202423810-0a012466-01ce-4f0e-ad9b-c6b1fcf76601.png">

My cluster operator version is rabbitmq-cluster-operator-3.1.0.

By the way, it works for port 5672 and 15672. And rabbitmq:3.7-management is ok for all the ports(1883, 15672 and 5672)

**Comment by janiu-001** [comment]
What does the "login timeout " mean?

**Comment by janiu-001** [comment]
@Zerpet @MirahImage  any other suggestions?

**Comment by janiu-001** [comment]
@Zerpet would you help to share your suggestions?

**Comment by janiu-001** [comment]
@MirahImage @Zerpet It is import for me, look forward for your suggestions

**Comment by Zerpet** [comment]
A login timeout means that the connection handshake between your client and the server did not complete correctly, within the expected time frame. The code comment suggests there could be a [resource alarm](https://rabbitmq.com/alarms.html). You would have to look into the server logs to determine if there's any resource alarm logged, and check using the [CLI](https://rabbitmq.com/rabbitmq-diagnostics.8.html#Monitoring,_observability_and_health_checks) if there's any active resource alarm. If you cluster does not have any resource alarm, you may try to enable debug logs in RabbitMQ, or check that your application code is doing the MQTT handshake as the protocol expects.

**Comment by janiu-001** [comment]
how to enable debug logs in cluster operator?

**Comment by janiu-001** [comment]
@Zerpet Thanks for your information,  the issue is solved.
