### ISSUE TITLE
Automatic management of the rabbitmq image.

### ISSUE THREAD

**Issue by farodin91** [rabbitmq/cluster-operator#1219]
**Is your feature request related to a problem? Please describe.**
Don't forget to update.

**Describe the solution you'd like**
Ideas:

-   adding checks to update only proper version.
-   a map of support version with the newest patch level to support upgrade of multiple versions
-   rate limit cluster upgrade speed.

**Additional context**
Other operators:

- Strimzi kafka (keeps a map of supported version, default updates to the newest version)
- zalando/postgres-operator (you can select a major version)

**Comment by DanielePalaia** [comment]
Hi @farodin91 thank you to have opened the issue linked to the PR we discussed and to have better documented the code.

I approved your contributions here: https://github.com/rabbitmq/cluster-operator/pull/1181

If you don't have other modifications to be done there I will integrate it
However this can be considered just a first experimental approach for testing purposes.

We document our environment variables here:
https://www.rabbitmq.com/kubernetes/operator/configure-operator-defaults.html#parameters

But as this functionality is still experimental, we can maybe avoid to document it at this stage and do it in a next stage.
