### ISSUE TITLE
Queues not rebalancing

### ISSUE THREAD

**Issue by MonicaMagoniCom** [rabbitmq/cluster-operator#1233]
I have deployed a cluster operator (2.0.0) together with a rabbitmqcluster (3.11.0) with 3 replicas and I've seen that when a replica is restarted, queues are not rebalanced. Even if I run **rabbitmq-queues rebalance all** from the replica bash, nothing happens.
I've also read that by default, the operator should reblance the queues when a change happens in the cluster. But in my scenario this does not happens. 

Any ideas?
Thank you

**Comment by MonicaMagoniCom** [comment]
The rebalance is executed but the queues remain distributed in the same way.
Here is the output:
Re-balancing leaders of classic queues...
┌────────┐
│ Output         │
├────────┤
│ [ ]                 │
└────────┘

All the queues are classic with no replication

**Comment by mkuratczyk** [comment]
Only replicated queues can be rebalanced with this command: quorum queues, streams and (deprecated) mirrored queues.

Basically this command changes which node hosts the leader for the queue/stream, from among the members of the queue. You only have one member, so nothing changes.

The ability to rebalance non-replicated queues is a valid request (it certainly came up in the past) but that's a (non-trivial) feature request for [RabbitMQ](https://github.com/rabbitmq/rabbitmq-server/), not a bug in the cluster operator.

**Comment by mkuratczyk** [comment]
(feel free to open that feature request)
