### ISSUE TITLE
Rebalance Queues When Node/Pod Restarts

### ISSUE THREAD

**Issue by si-c613** [rabbitmq/cluster-operator#1242]
**Is your feature request related to a problem? Please describe.**
We provision our RabbitMQ Pods onto dedicated Nodes created by Karpenter.
We also use [Karpenters Node `ttlSecondsUntilExpired`](https://karpenter.sh/v0.23.0/concepts/deprovisioning/) feature to cycle our Nodes every 24h to make patching and other such TOIL easier.

When a RabbitMQ Node expires it is drained and the RabbitMQ Pods are terminated according to a Pod Disruption Budget allowing only a single Pod to be `unavailable` at a time.

We end up in a situation where all classic queue leaders are on a single Pod as described in the [design doc](https://github.com/rabbitmq/cluster-operator/blob/main/docs/design/20200520-graceful-pod-termination.md#balancing-the-cluster).

**Describe the solution you'd like**
Currently an annotation `rabbitmq.com/queueRebalanceNeededAt` is added to the `Rabbitmqcluster` CR if the StatefulSet has been updated, according to the logic [here](https://github.com/rabbitmq/cluster-operator/blob/main/controllers/reconcile_cli.go#L119-L123) and [here](https://github.com/rabbitmq/cluster-operator/blob/main/controllers/reconcile_cli.go#L129-L131), checking if the StatefulSets `status.CurrentRevision` and `status.UpdateRevision` are equal.
This works for when the StatefulSet is being updated or a restart/rollout of the StatefulSet has been triggered either by the Cluster Operator or by other Kubernetes processes.

However when a Node or Pod is restarted individually the StatefulSet isn't updating so the annotation is not added.

It would be good if other Kubernetes events could trigger this annotation and a queue rebalance.

Perhaps making use of the [`allReplicasReadyAndUpdated`](https://github.com/rabbitmq/cluster-operator/blob/edb53aaaeddea30a6b7a1a2f856ea3d3355ef18e/controllers/reconcile_cli.go#L125-L127) function in addition to testing if the StatefulSet is updating.

**Describe alternatives you've considered**
I've looked into adding a `postStart` hook to trigger the rebalance, however this runs before RabbitMQ is ready so needs some more work to wait for this condition, but then that risks a timeout.

Other alternatives include running the rebalance as a CronJob in the cluster. but this also risks running the rebalance too often.

**Additional context**
NA

**Comment by mkuratczyk** [comment]
Are all the nodes recreated around the same time? For a rolling restart, we wait for all pods to be restarted and trigger rebalancing once. Could this be done similarly in your case? Being smarter about rebalancing would be nice but I'm not sure what trigger we could use in this case. Perhaps the easiest would be for you to just trigger the rebalance when you know it is needed? 🤔

**Comment by si-c613** [comment]
> Are all the nodes recreated around the same time?

Unfortunately not, the Karpenter Provisioner gives a Kubernetes Node a TTL of 24h so it depends when the Node was started. 
Originally they were all sequential but due to issues in the cluster they are now spread across a 24h period due to being restarted at different times. (TL;DR we have memory issues we are hoping this helps with, that blocked shutdowns of Nodes)

> For a rolling restart, we wait for all pods to be restarted and trigger rebalancing once. Could this be done similarly in your case?

Allowing for the fact that not all Nodes may be restarted sequentially and the rebalance was triggered when the cluster was stable/healthy this is exactly what we are looking for.

> Perhaps the easiest would be for you to just trigger the rebalance when you know it is needed?

We'd love to do this, but it's been known for the Nodes to restart out of hours so having someone trigger the rebalance wouldn't be feasible. Also what if a Node is terminated for other reasons at anti social hours (hardware/data centre failure etc).


I've run the code through a debugger and can see that the reconciliation loop is triggered by the Pod restarts, however the test to see if the STS is being updated stops the Annotation being added to the RMQ CR.
I wonder if adding [`allReplicasReadyAndUpdated`](https://github.com/rabbitmq/cluster-operator/blob/main/controllers/reconcile_cli.go#L125-L127) into the conditional (i.e. if STS is updating or the Replicas aren't all healthy) would solve the problem. My only consideration is I'm not sure under what other circumstances this would trigger the rebalance and if any of those would be undesirable. Although this would only trigger on Pod restarts which I believe is the time that rebalances are desired to run.

**Comment by mkuratczyk** [comment]
Current Operator versions support RabbitMQ 3.9.9+ (and 3.9 support ends today). This doesn't invalidate your request but even if we shipped it tomorrow (and I'm fairly sure we won't ;) ) you basically won't be able to take advantage of it until you at least upgrade to the latest 3.9. I'd highly recommend to upgrade to at least 3.10 as it significantly reduced quorum queue memory usage.

**Comment by si-c613** [comment]
Thanks, I was aware of that when I raised and we are still using v1 of the operator. :)
I won't pollute with the details but we are about to break the link to a 3.7 cluster so we can start upgrading. 

I raised this cause I do think it's a good thing to have even if we won't see the benefit for a while
