### ISSUE TITLE
The "rabbitmq-cluster-operator" get stuck on "ErrImagePull" in a Kubernetes Cluster with Windows nodes

### ISSUE THREAD

**Issue by Corbeau3000** [rabbitmq/cluster-operator#1261]
## Describe the bug
The cluster operator is unable to deploy and stays at the "ErrImagePull" status.

## To Reproduce
1. Create a Kubernetes Cluster with 2 nodes, one Control Plane on Linux (untainted) and another worker node on Windows.
2. Deploy the cluster operator (ex : kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/download/v2.1.0/cluster-operator.yml")
3. See the error on the pod "pod/rabbitmq-cluster-operator-...." 

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m52s                  default-scheduler  Successfully assigned rabbitmq-system/rabbitmq-cluster-operator-956674b95-chg6q to win2019min
  Normal   Pulling    4m30s (x4 over 5m52s)  kubelet            Pulling image "rabbitmqoperator/cluster-operator:2.1.0"
  Warning  Failed     4m29s (x4 over 5m51s)  kubelet            Error: ErrImagePull
  Normal   BackOff    45s (x20 over 5m51s)   kubelet            Back-off pulling image "rabbitmqoperator/cluster-operator:2.1.0"

**Expected behavior**
The Pod should deploy to a Linux node

## Version and environment information
- RabbitMQ: 3.10.2
- RabbitMQ Cluster Operator: 2.1.0
- Kubernetes: 1.25.6
- On-prem cluster (Ubuntu 22.10 / Windows Server 2019 Standard)
 

## Additional context
There should be a nodeSelector specified for the deployment.

**Comment by DanielePalaia** [comment]
Hi @Corbeau3000 unfortunately at moment we don't have an hybrid test environment using a K8s node deployed on a windows machine. But this shouldn't be an issue.

But just to better understand your issue, are you able from your windows node to schedule any other pod/app where the image is hosted on dockerhub? Are you able from this windows node to docker pull an image from github from example?

Regarding the node selector option with the cluster operator OSS we provide a manifest file. You can use for example kustomize to  add/modify the option you prefer.

**Comment by DanielePalaia** [comment]
Hi @Corbeau3000. A lot of time passed since we requested the informations without response. I assume at this point this was an environment issue or got solved somehow. I will close this issue, feel free to open a new one in case you are meeting new problems.
