### ISSUE TITLE
Provide Prometheus-Rules via Helm chart

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rabbitmq/cluster-operator#1268]
**Is your feature request related to a problem? Please describe.**
Looks like the prometheus-rules https://github.com/rabbitmq/cluster-operator/tree/main/observability/prometheus/rules/rabbitmq are not available via the helm install template? 

**Describe the solution you'd like**
Add a helm value to enable deploying of prometheus rules

**Describe alternatives you've considered**
Applying them manually, but this is not my desired deployment method since I use helm: https://artifacthub.io/packages/helm/bitnami/rabbitmq-cluster-operator

**Comment by DanielePalaia** [comment]
HI @h0jeZvgoxFepBQ2C our colleagues from Bitnami suggested to open a discussion/issue on their repo https://github.com/bitnami/charts, so that they will evaluate the possibility to do this implementation!
