### ISSUE TITLE
How to load rabbitmq_delayed_message_exchange

### ISSUE THREAD

**Issue by jiuker** [rabbitmq/cluster-operator#1306]
How to load rabbitmq_delayed_message_exchange plugin?

**Comment by mkuratczyk** [comment]
We have an example how it can be accomplished: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/community-plugins

It's not necessarily The Way you want to do it though: it assumes access to the Internet (or at least some other place if you change the URL) and is a potential security risk if that file is modified. But this should get you started.

**Comment by jiuker** [comment]
@mkuratczyk It's not good idea for offline.May be I will Do 
```Dockerfile
From rabbitmq-server:3.8.8
curl plugins
```

**Comment by mkuratczyk** [comment]
Up to you really. Personally I consider this a missing piece in the Kubernetes ecosystem. Maybe I'm missing something but I'd love to be able to specify an OCI image as a volume. Then in situations like this (no just for RabbitMQ, but anything that may need some additional plugins or tools), these plugins could be distributed as trivial OCI images (an image disk without any way to run it on its own)
