### ISSUE TITLE
Operator is vulnerable to misoperations and drives the cluster to broken state

### ISSUE THREAD

**Issue by hoyhbx** [rabbitmq/cluster-operator#1324]
Hello rabbitmq operator developers,

We found that many properties in the CR are very easy to drive the cluster into a broken state if not handled carefully.
For example, when specifying a bad value for the properties in `spec.rabbitmq.advancedConfig`, the operator will perform a rolling upgrade and the restarted pod will crash because of invalid config. There are a lot of other examples include `spec.Affinity`, `spec.rabbitmq.envConfig`, `spec.tolerations`.

A concrete example is to submit the following CR
```
spec:
  rabbitmq:
    advancedConfig: "config with typo"
...
```
cluster-operator updates the statefulSet which triggers a rolling update, but the newly started rabbitmq pod cannot be started.

It causes severe consequences in production. We believe these are misoperation vulnerabilities where the operator fails to reject the misoperation from users. The operator uses controller-gen to automatically generate validations for many properties, but these static validations fall short for validating more complicated contraints, e.g. to reject an invalid nodeSelector needs knowledge of which nodes are available in Kubernetes cluster. Validating the rabbitmq configuration also requires application specific information.

We want to open this issue to discuss what do you think should be the best practice to handle this issue, or what functionalities should the Kubernetes provide to make this validation easier. Is there a way to prevent the bad operation from happening in the first place, or there is a way for cluster-operator to automatically recognize the statefulSet is stuck and perform an automatic recovery. If you know of any practical code fixes for this issue, we are also happy to send a PR for that.

**Comment by lukebakken** [comment]
> There are a lot of other examples

If you could provide concrete examples that would be very useful.

In the case of `advanced.config` the most basic check would be to run something like the following:

```
erl -noinput -boot no_dot_erlang -eval 'RV = case file:consult("bad-advanced.config") of {ok,_} -> 0; _ -> 1 end, halt(RV).'
```

The above returns `1` for a file with this content:

```
C:\Users\bakkenl\development\lukebakken\rabbitmq\conf [main ≡ +2 ~1 -0 !]
> erl -noinput -boot no_dot_erlang -eval 'RV = case file:consult("bad-advanced.config") of {ok,_} -> 0; _ -> 1 end, halt(RV)'; echo $LASTEXITCODE
1

C:\Users\bakkenl\development\lukebakken\rabbitmq\conf [main ≡ +2 ~1 -0 !]
> cat .\bad-advanced.config
"this is invalid"
```

...and for a valid file:

```
> erl -noinput -boot no_dot_erlang -eval 'RV = case file:consult("advanced.config") of {ok,_} -> 0; _ -> 1 end, halt(RV).'; echo $LASTEXITCODE
0
```

Note that this check only ensures the structure of the file is valid, but does not validate the contents as valid RabbitMQ settings.

**Comment by hoyhbx** [comment]
Other examples include submitting a seemingly correct toleration rule:
```
spec:
  tolerations:
  - effect: NoSchedule
    key: ""
    operator: Equal
    value: test-value
```
but the rabbitmq Pod fails to be created with error message from statefulSet
```
Pod "test-cluster-server-2" is invalid: spec.tolerations[0].operator: Invalid value: "": operator must be Exists when `key` is empty, which means "match all values and all keys"
```

Failure could also happen if users specify a syntactically correct Affinity rule, but not satisfiable.

These errors are indicating that there are some validation done in the system, but these validations are done too late where there are already Pods down in the cluster.
The problem would be solved if operator could call some validation function from statefulSet or from rabbitmq and reject the misoperations early.

I am not sure if the operator should reimplement all the validation logics from all Kubernetes builtin controllers and the Rabbitmq system. It seems that some support is needed from both the Kubernetes infrastructure and Rabbitmq system so that operator can easily validate the operations without rebuilding all the wheels.

**Comment by Zerpet** [comment]
You can use [Open Policy Agent](https://www.openpolicyagent.org/), or a [validating webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/), to reject those operations before they reach the Operator. 

The example you gave for tolerations is something we, on purpose, did not add to the Operator, because we would be duplicating Kubernetes validations, and that adds toil to maintain, in the form of having to track upstream Kubernetes to keep those validations updated. The same applies to any validation performed by Kubernetes itself.

> It causes severe consequences in production.

This would arguably have an impact to production, if you apply your changes to a dev or staging environment, before applying to production. The Operator can't safeguard against everything, and not validating changes before applying to production is quite brave.
