### ISSUE TITLE
Is it possible to integrate the hashicorp vault rabbitmq engine?

### ISSUE THREAD

**Issue by SnoozeFreddo** [rabbitmq/cluster-operator#1385]
Currently i would have to set credentials beforehand. However i would like to generate secrets dynamically as described [here](beforehand). Is it possible?

**Comment by MirahImage** [comment]
There is an example for integrating with vault https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/vault-default-user

**Comment by MirahImage** [comment]
The link you've provided in the issue is broken, can you please fix it?

**Comment by SnoozeFreddo** [comment]
Sadly, even i couldn't find the issue i was referencing any more but i solved my problem in a different way anyway. Thank you!

**Comment by headyj** [comment]
@SnoozeFreddo may I ask you how you solved your problem? I try to do the same (pushing autogenerated credentials to Vault) but without success. I was considering using crossplane vault-provider but the generated secret doesn't have the right format
