### ISSUE TITLE
Support s390x Architecture

### ISSUE THREAD

**Issue by Joshua-Beha** [rabbitmq/cluster-operator#1396]
**Is your feature request related to a problem? Please describe.**
Currently, I cannot run the RabbitMQ operator on s390x as the [images on Dockerhub](https://hub.docker.com/r/rabbitmqoperator/cluster-operator/tags) are built only for arm64 and amd64.

**Describe the solution you'd like**
I would like to run the RabbitMQ operator on s390x using officially available images

**Describe alternatives you've considered**
I have considered attempting to build the images myself.

**Additional context**
Support for ppc64le would also be cool.

**Comment by mkuratczyk** [comment]
How about a pull request? There's literally one company in the world that needs this :)

**Comment by michaelklishin** [comment]
This is open source software. The way open source software works is that those with very specific needs have the tools to scratch their own itch.

I find this particularly important to mention because this one aforementioned company never contributed to RabbitMQ, despite offering for $$$ as a service.

**Comment by michaelklishin** [comment]
I suspect that the image used is the Docker community one, so this issue does not belong to this repo https://github.com/docker-library/rabbitmq

**Comment by Joshua-Beha** [comment]
Hi @mkuratczyk and @michaelklishin after some further investigation the RabbitMQ cluster operator pod can be built on s390x without changes using the [Dockerfile](https://github.com/rabbitmq/cluster-operator/blob/86e5de3f624fcaadbfb99cf94033ad6454f4a271/Dockerfile) in **this** repository.
Following the quick start guide in your README I was able to deploy the operator and stand up a cluster without issue on an s390x OpenShift cluster. Are there other tests you would like me to run to test for compatibility?

**Comment by Joshua-Beha** [comment]
Also, I don't know what the RabbitMQ Cluster Operator uses for a build process but I could make some changes there if required. It looks like someone in the RabbitMQ community can build for s390x given the RabbitMQ pod is available for s390x (see [here](https://hub.docker.com/_/rabbitmq)), so I would assume it would also be possible here.
