### ISSUE TITLE
Refactor RabbitmqCluster CRD to achieve full flexibility

### ISSUE THREAD

**Issue by st3v** [rabbitmq/cluster-operator#14]
**Is your feature request related to a problem? Please describe.**
We would like the `RabbitmqCluster` CRD to be as flexible as possible. That means the user of that CRD should be able to tweak pretty much ...
1. any property on most of the child resources of the `rabbitmqcluster` resource (and in some cases the grandchildren)
2. any property that can be configured in RabbitMQ itself (config file, plugins, etc)

To achieve this we will have to refactor the current CRD as it doesn't support any of the above. One pattern we have seen with some of the K8s core resources is to add templates for the children to the parent CRD (e.g. pod template for stateful sets). This seems to be something that would make sense here too.

This issue is meant to track the work to come up with an initial proposal. Subsequent implementation work will be tracked in separate issues in the future.

**Describe the solution you'd like**
Create a proposal for what a fully flexible `rabbitmqcluster` CRD might look like.

**Describe alternatives you've considered**
See upcoming proposal that will be created as part of this issue.

**Additional context**
There's some [pre-existing work](https://github.com/pivotal/rabbitmq-for-kubernetes/tree/wip-api-changes/api/v1beta2).

**Comment by ChunyiLyu** [comment]
Closing because this is done.
