### ISSUE TITLE
The v.2.x.x versions are not importable

### ISSUE THREAD

**Issue by gibizer** [rabbitmq/cluster-operator#1407]
## Describe the bug
The v2.x.x versions cannot be imported to another go project.

The https://github.com/golang/go/wiki/Modules#semantic-import-versioning states that:
>  If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1)

It seem this is not followed and therefore go mod fails to pick up the new major version:

```
$ GOPROXY="direct" go list -m --versions github.com/rabbitmq/cluster-operator
github.com/rabbitmq/cluster-operator v1.0.0 v1.1.0 v1.2.0 v1.3.0 v1.4.0 v1.5.0 v1.6.0 v1.7.0 v1.8.0 v1.8.1 v1.8.2 v1.8.3 v1.9.0 v1.10.0 v1.11.0 v1.11.1 v1.12.0 v1.12.1 v1.13.0 v1.13.1 v1.14.0
```

```
$ GOPROXY="direct" go list -m --versions github.com/rabbitmq/cluster-operator/v2
go: loading module retractions for github.com/rabbitmq/cluster-operator/v2@v2.0.0: version "v2.4.0" invalid: go.mod has non-.../v2 module path "github.com/rabbitmq/cluster-operator" (and .../v2/go.mod does not exist) at revision v2.4.0
```

## To Reproduce
1. go list -m --versions github.com/rabbitmq/cluster-operator
2. go list -m --versions github.com/rabbitmq/cluster-operator/v2

**Expected behavior**
v2 versions are listed

## Screenshots
N/A

## Version and environment information
N/A
 
## Additional context
We are importing this operator in https://github.com/openstack-k8s-operators/infra-operator

**Comment by Zerpet** [comment]
Looks like we missed updating the `go.mod` when we created a new major. In fairness, I didn't expect people to import our code 😅 Thank you for reporting this!
