### ISSUE TITLE
Change port order for k9s

### ISSUE THREAD

**Issue by tamis-laan** [rabbitmq/cluster-operator#1414]
So when deploying a `RabbitmqCluster` and using the port forward feature from k9s the default port that is chosen to be forwarded is set as the first port in the list of exposed ports:

![screenshot](https://github.com/rabbitmq/cluster-operator/assets/3178666/020cd0f9-3246-42f9-856d-9d43036d6eb3)

Can we change the order such that the management console is the first in the list?

I'm not sure about other kubernetes GUI's but I'm assuming there it's the same issue.

**Comment by mkuratczyk** [comment]
I see no reason not to do that but it needs to be done carefully as it triggers a rolling restart, even though the result is ultimately the same. I'm pretty sure users would rather not have the clusters restarted just for this.

@tamis-laan is this something you could contribute a PR for?
