### ISSUE TITLE
Add version compatibility to the README

### ISSUE THREAD

**Issue by j4mcs** [rabbitmq/cluster-operator#146]
**Is your feature request related to a problem? Please describe.**
We currently don't explicitly lay out our minimum required versions of RabbitMQ and Kubernetes

Kubernetes version is constrained by our use of the OpenAPI schema to v1.16+ (?) 
RabbitMQ version is constrained by the `rabbitmq-queues` checks in the lifecycle hook (introduced in v3.83)

**Comment by ChunyiLyu** [comment]
This is done. Closing
