### ISSUE TITLE
Update upgrade job in pipeline according to rebranding efforts

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#152]
## Why
Our [upgrade pipeline](https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/upgrade) has been failing since we merged #140 because it is expects a deployment with name `p-rabbitmq-operator` to be present. 

## What 
We don't deploy with this name anymore so we should update our pipeline to match the new name and make it green again 🟢

**Comment by ChunyiLyu** [comment]
We decided to remove the pipeline all together. See: https://github.com/rabbitmq/cluster-operator/issues/322
