### ISSUE TITLE
rabbitmq cluster operator

### ISSUE THREAD

**Issue by alter** [rabbitmq/cluster-operator#1583]
Em... why you deleted my issue?

**Comment by lukebakken** [comment]
Because there is no evidence of a bug. If we find an actual bug, we will create an issue.

Please follow-up here: https://github.com/rabbitmq/cluster-operator/discussions/1582

Especially this comment: https://github.com/rabbitmq/cluster-operator/discussions/1582#discussioncomment-8747200
