### ISSUE TITLE
rabbitmq operator watch configmaps when configmaps too many and large it will failed

### ISSUE THREAD

**Issue by jisongxi** [rabbitmq/cluster-operator#1588]
version 1.14.0

when I create the rabbitcluster , but no pod and sts created, i see the log from the operator pod as this:
![image](https://github.com/rabbitmq/cluster-operator/assets/9650220/417fcf28-47eb-4f00-819d-d93e01a6c6b6)
how to fix the problem

**Comment by mkuratczyk** [comment]
This seems to be an issue with your Kubernetes cluster, not a RabbitMQ / cluster operator issue.
Kubernetes API responds with a "internal error".

As additional evidence, a completely different project had a virtually identical issue reported and reached a similar conclusion:
https://github.com/fluxcd/source-controller/issues/1137

**Comment by jisongxi** [comment]
My k8s cluster has a lot of configmaps. Can rabbitmq operator only monitor the required configmaps? Is it because there are too many configmaps, causing rabbtimq to pull the configmap reading of the entire cluster and time out?

**Comment by mkuratczyk** [comment]
If that's what causes the problem, it's likely fixed on the `main` branch already: https://github.com/rabbitmq/cluster-operator/pull/1549

We need to ship a new version with this change though
