### ISSUE TITLE
Operator open source docs

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#171]
- We will use rabbitmq.com docs
- It would be a mix of migrating some of the bits we have in Pivotal docs and rewriting some other bits to include less basic options (Pivotal docs missing 'additionalPlugins' and 'additionalConfig')
- [Link](https://docs.pivotal.io/rabbitmq-kubernetes/0-7/index.html) to latest released docs in TanzuNet.

An overview of the task I foresee this will entail:

- [x] Lift, shift and adapt current docs to new format
- [x] Update installation guide to:
  - [x] remove references to PivNet/TanzuNet
  - [x] show how to build the docker image
  - [x] explain how to deploy using `kustomize`
- [x] Update installation with Helm to:
  - [x] use the local chart folder
  - [x] document values file
- [x] Remove bits to Container Service Manager (KSM) ❓ 
- [x] Prometheus and Grafana monitoring

**Comment by ansd** [comment]
Docs are published.
