### ISSUE TITLE
How can I override the erlang cookie?

### ISSUE THREAD

**Issue by shezaan-hashgraph** [rabbitmq/cluster-operator#1753]
While I see that external secrets can be used to override the default username and password, I did not find an easy way to override the erlang cookie. How can this be achieved? Any example you can provide would be very helpful. Please and thank you. I am using the latest version of the cluster-operator.

**Comment by Zerpet** [comment]
We didn't have a convincing use case to implement this. Would you share your use case to change the erlang cookie?

Note as well that there are some caveats and operational headaches related to changing the cookie. For example, cookie cannot be change in a rolling update fashion, it's a stop-the-world kind of change. This doesn't play very well with Kubernetes and StatefulSets, which tries to update one Pod at a time.

**Comment by Zerpet** [comment]
That was our intention 🙂 The Operator will take care of many operational tasks of deploying rabbit, so that you can focus on actually using rabbit and build great things 🚀
