### ISSUE TITLE
RabbitMQ instance does not get updated

### ISSUE THREAD

**Issue by tormig-softronic** [rabbitmq/cluster-operator#1772]
## Describe the bug
We stepped through operator versions from 2.8 to 2.10 and each time we had to remove an image statement in the RabbitmqClusters manifest to get the RabbitMQ instans updated.

`spec:
  delayStartSeconds: 30
  secretBackend:
    externalSecret:
      name: ''
  resources:
    limits:
      cpu: '1'
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 2000Mi
  terminationGracePeriodSeconds: 604800
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            priorityClassName: iis-dev-prio
            securityContext: {}
  service:
    type: ClusterIP
  tls: {}
  image: 'rabbitmq:3.13.7-management'
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
      - rabbitmq_shovel_management
  persistence:
    storage: 10Gi`

We don't have the image line in our file, it is added by the operator. After an upgrade of the Operator that line remains the same. If you then remove it it will re-appear with the correct image. 

It does however restart the RabbitMQ instance but just with the old (previous) image.

**Comment by mkuratczyk** [comment]
That's working as expected. There is no tight coupling between the operator version and the RabbitMQ version. Therefore, when you upgrade the operator, existing RabbitMQ instances are not upgraded (in terms of the RabbitMQ version, they might be restarted with some Statefulset adjustments). When you delete the `image` value, the operator injects the default version, which will be different between different operator versions.

If you want to upgrade RabbitMQ, just change the `image` value to the version you want. RabbitMQ is released more often than the operator, so the default of the operator, even when running the latest operator version, is usually behind the latest RabbitMQ version.

**Comment by mkuratczyk** [comment]
Changing the `image` value of a `RabbitmqCluster` resource is THE way to upgrade RabbitMQ. As for operator<->RabbitMQ version compatibility, there is no 100% compatibility, incompatibilities has been rare and mostly happened in the early days of the operator's existence. For example, when RabbitMQ 4.0 was released, there was no corresponding Operator release, because the there was no need - existing Operator worked fine[1] with 4.0.

[1] later on one incompatibility was found and fixed.
