### ISSUE TITLE
Consider support for CSI store driver

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#182]
[Kubernetes CSI store driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver)  integrates secrets stores with Kubernetes via a Container Storage Interface (CSI) volume. The Secrets Store CSI driver secrets-store.csi.k8s.io allows Kubernetes to mount multiple secrets, keys, and certs stored in enterprise-grade external secrets stores into their pods as a volume. Once the Volume is attached, the data in it is mounted into the container's file system.

We might indirectly already support it with overrides but we need to test it. Even then, let's consider whether this should be a top-level feature.

**Comment by kamilzzz** [comment]
I assume it was decided support for CSI secret store driver won't be a top level feature, right?
