### ISSUE TITLE
Invstigate different Operator base images

### ISSUE THREAD

**Issue by coro** [rabbitmq/cluster-operator#194]
**Is your feature request related to a problem? Please describe.**
Currently, for the operator image we use a [pinned version of Ubuntu Bionic](https://github.com/rabbitmq/cluster-operator/blob/a8465dd1be35b4f3caf3a3fb3b1c35b04a8987de/Dockerfile#L19) as the base image. While this made sense at the time, this process is no longer suitable: pinning to a particular SHA causes us to miss out on security updates to the base image.

In addition, Ubuntu Docker images are fairly large (64.2MB), compared with some other alternatives available, such as Alpine (5.57MB) or Google Distroless (1.79MB). Larger images contain much more software than the operator needs, and theoretically increases the surface area for security vulnerabilities. In contrast, larger traditional distros such as Debian & Ubuntu have larger communities maintaining them, and this may lead to faster CVE fixing than the likes of Alpine & Distroless.

**Describe the solution you'd like**
At the very least, we should bump to the latest version of the Bionic image to consume the latest fixes for the image.

We could also potentially switch to a different distro like Alpine, or go distroless altogether. Some investigation into what's possible/optimal would be useful.

**Describe alternatives you've considered**
Debian is an alternative to Ubuntu, but appears to be on par in terms of security from what I can tell (happy to stand corrected).

**Additional context**
Kubebuilder, by default, uses Google's Distroless base image in [Dockerfiles it generates](https://github.com/kubernetes-sigs/kubebuilder/blob/6e0d3d4f18ecdc335177d28e1d6cd4d7b2930242/pkg/plugin/v2/scaffolds/internal/templates/dockerfile.go#L62).

Considerations to be made on which image is used:
* Size of image
* Security profile of image
  * Frequency & severity of CVEs
  * Speed with which CVEs are typically fixed
* Whether the image provides / can provide utilities necessary to the operator (~~`useradd` & `groupadd` come to mind~~ looks like you can do this in distroless by providing a custom `/etc/groups` and `/etc/passwd` to the image)
* Performance of the operator running on the image

**Comment by coro** [comment]
Looks like we also had concerns about whether distroless had timezone data & CA certs for TLS. According to [the README](https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md) for the images, it has tzdata and ca-certificates.

**Comment by coro** [comment]
Copying over from a Slack discussion about this:

Requirements (as far as I can tell):

- Can run the manager binary (Go is statically linked so we don't need any libraries in the base image)
- Minimal surface area for attack (A manager image built on distroless is 46MB, 43MB of which is the manager binary)
- Quick patches to CVEs (Looks like they have [Github actions](https://github.com/GoogleContainerTools/distroless/actions) to bump base images every day)
- Ability to add a custom user with UID & GID 1000, name rabbitmq-cluster-operator (can do this through a custom `/etc/group` & `/etc/passwd` entry)
- Access to timezone data in order to use the Go `time` library (`tzdata` [is included](https://github.com/GoogleContainerTools/distroless/tree/master/base#documentation-for-gcriodistrolessbase-and-gcriodistrolessstatic) in the distroless image, so this is no longer an issue)
- Ability to perform TLS verification (`ca-certificates` [is included](https://github.com/GoogleContainerTools/distroless/tree/master/base#documentation-for-gcriodistrolessbase-and-gcriodistrolessstatic) in the base image - `libssl`/`openssl` is not but Go uses its own TLS library)

To me it seems the distroless image does everything we need it to, as well as matching a commonly-held practice in the community of using minimal images for better security. One argument I could see is that by default the image does not have shell access, so if one needed shell access to the operator, one would have to rebuild using a different base image, but I see that as a minor inconvenience compared to generally better security principles.

**Comment by MirahImage** [comment]
Given go 1.15 now includes the timezome data necessary to use the `time` library within the golang distribution itself, we have one less requirement for the base image. It might be worth investigating whether we can even get away with shipping an image based on SCRATCH (aka an empty base).
