### ISSUE TITLE
1-step installation

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#228]
**Is your feature request related to a problem? Please describe.**
Our current [installation guide](https://www.rabbitmq.com/kubernetes/operator/install-operator.html#using-kubectl-yaml) has a number of steps that are not "beginner friendly", for example building your own Docker image or clonning the repo. These steps assume developer experience with Git and with Docker, which might not be true for some users of this project, who might have a more "IT-ops" kind of background. We should make the installation experience as simple as possible.

**Describe the solution you'd like**
Inspired by project [Antrea](https://github.com/vmware-tanzu/antrea/blob/master/docs/getting-started.md#installation), we should aim to have an installation method as simple as `kubectl apply -f <github-url/to/a/file.yaml>`. Kubectl already supports pointing to URLs and it has a built-in module for `kustomize` files, which can be invoked using `kubectl apply -k <github-url>//path/to/some/folder/`. We might need to create a new kustomization folder, or change the current layout (dangerous) to achieve this.

Examples of the above working for this repo. Please note that the double forward slash is intended and required:

```bash
kubectl create -k github.com/rabbitmq/cluster-operator//config/namespace/
kubectl create -k github.com/rabbitmq/cluster-operator//config/crd/
```

**Describe alternatives you've considered**
Using pure `kustomize` is also posible e.g. `kustomize build github.com/rabbitmq/cluster-operator//config/rbac/`, however the adoption and use of `kustomize` is not guaranteed and some users might not have this tool installed. It is almost guaranteed that a Kubernetes user will have `kubectl` installed, therefore we should favour the use `kubectl` when possible.

**Additional context**
We can't invoke `kubectl create -k github.com/rabbitmq/cluster-operator//config/default/base/` because it will try to load files from `../some/other/location`, which won't exist if we use this method..

Git should be aware of symlinks, it's worth trying out and exploring if a "central" folder with symlinks to other resources can be a solution.

**Comment by coro** [comment]
Seems like there's a tradeoff here - since we're using kustomize either way (either packaged in kubectl or directly), we should consider whether we're happy having kustomize integration pinned to v2.0.1 (packaged in kubectl) and potentially not function with the latest kustomize (we've been using v3.7.0). Seems like if we go down the `kubectl create -k` route then we're adopting the former.

**Comment by coro** [comment]
We could per-version create a manifest that is the output of the kustomize commands we would run, using the up-to-date kustomize. We could automate this in CI and release with new versions of the operator as an asset attached to the GitHub release. That way the one-step install (that would be versioned!) could be something like:

```
kubectl create -f https://github.com/rabbitmq/cluster-operator/releases/download/$RMQ_OPERATOR_VERSION/rabbitmq-cluster-operator_$RMQ_OPERATOR_VERSION.yaml
```

**Comment by mkuratczyk** [comment]
With last week's updates to the installation procedure, we are really close to achieving this. In https://www.rabbitmq.com/kubernetes/operator/install-operator.html we now ask users to run a few `kubectl` commands to generate and apply YAML but we could just generate it on our side as part of the release process (there is no user input anyway) and then users could just apply a single YAML file.

We should do something like this:
1. on every merge to main (or when we want to cut a release but I think we can start with "on every merge")
2. build a new image (already happens) and tag it (ideally according to whatever we decide in https://github.com/rabbitmq/cluster-operator/issues/190)
3. merge namespace.yaml, rabbitmq.com_rabbitmqclusters.yaml and the output of the two `kustomize` commands that we have into a single file
4. hardcode the image tag to the tag/version from the previous step
5. publish that YAML file as a release asset on github

This should allow a single `kubectl apply -f https://` to deploy any specific version and hopefully thanks to github, using /releases/latest in the URL should simply deploy the most recent release (it could be a separate issue in the future but deploying `latest` should still make it clear which version is actually running)

For users who relocate the image need to change it in the YAML. Right now we suggest using `kustomize` for that (https://www.rabbitmq.com/kubernetes/operator/install-operator.html#relocate-image) but with this new single-YAML-file approach, that would need to change.

**Comment by harshac** [comment]
We will also need to modify the installation docs as a part of this issue.

**Comment by Zerpet** [comment]
## Context

Submitted a PR to adapt a make target to generate a single-file manifest file. Our pipeline already publishes releases to this repo. The idea is that the pipeline will generate the installation manifest, with version specific tag and publish this manifest as part of the release. Then it will be as simple as 

```
kubectl create -f https://github.com/rabbitmq/cluster-operator/releases/download/v1.2.3/rabbitmq-cluster-operator.yaml
```

As part of this issue, we will also update the docs to utilise this method. The use case of private repos can be accomodated by downloading the generated manifest and changing the image name. Some guidance around image relocation may be provided.

**Comment by Zerpet** [comment]
This PR https://github.com/pivotal/rabbitmq-for-kubernetes-ci/pull/11 will make the necessary changes to produce releases with an installation manifest.

**Comment by Zerpet** [comment]
https://github.com/pivotal/rabbitmq-for-kubernetes-ci/pull/11 and #297 are merged. The next commit to the main branch will produce an artefact with the release manifest. Closing this issue 🐇
