### ISSUE TITLE
Rename enabled_plugins to default_plugins

### ISSUE THREAD

**Issue by harshac** [rabbitmq/cluster-operator#233]
The enabled_plugins property name in the configMap is confusing. It contains the always_enabled_plugins and first set of additionalPlugins provided in the spec. Any subsequent change to additionalPlugins is not reflected in the `enabled_plugins` value in configMap.

This can be confusing especially when a user has disabled a plugin and still sees it the `enabled_plugins` list. 

**Solution**
One of the solutions could be to rename the `enabled_plugins` to `default_plugins` and only add the plugins which we always enabled and not the ones from `additionalPlugins`

E.g. 
`apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq-plugins-test
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
`

The config map looks like
`$ kubectl get -o yaml cm rmq-plugins-test-rabbitmq-server-conf`

`apiVersion: v1
data:
  default_plugins: '[rabbitmq_peer_discovery_k8s,rabbitmq_prometheus,rabbitmq_management].'
...`
The above list does not contain the user request `rabbitmq_mqtt` plugin. 

**Alternative**
Other approach is to update the list of enabled_plugins with changes in additionalPlugins. Although this would mean a pod restart which is not necessary in case of plugins.

**Comment by mkuratczyk** [comment]
I think this pretty much a duplicate of https://github.com/rabbitmq/cluster-operator/issues/224. If we implement https://github.com/rabbitmq/cluster-operator/issues/224 as suggested, by separating `enabled_plugins` into a dedicated ConfigMap, then we can implement enabling and disabling plugins as `rabbitmq-plugins set` **and** an update to the ConfigMap. This will fix https://github.com/rabbitmq/cluster-operator/issues/224 but also make the list always up to date as requested in this issue.

**Comment by harshac** [comment]
I will close this issue then.
