### ISSUE TITLE
Any thoughts/plans on integration with OSBAPI / cloud foundry marketplace?

### ISSUE THREAD

**Issue by aegershman** [rabbitmq/cluster-operator#238]
**Is your feature request related to a problem? Please describe.**

In order to integrate the rabbitmq cluster-operator with provisioning through the cloud foundry marketplace, it'd be valuable to know how/if there is a story around how the rmq cluster operator can be leveraged to provision, update, and bind rmq instances through the cloud foundry marketplace / OSBAPI

**Describe the solution you'd like**

Whether there are thoughts or a vision on how rmq clusters would be managed and bound through the cf marketplace, or whether that's something a bit further out

**Describe alternatives you've considered**
n/a

**Additional context**
not looking for a definitive answer, just curious if there is any ideas floating out about how rmq instances could/would be wired up to CF, or if it's something that's not being thought about at the moment

thanks all 👍

**Comment by mkuratczyk** [comment]
Hi,

It's possible to integrate RabbitMQ Cluster Operator with OSBAPI through [KSM](https://docs.pivotal.io/ksm/0-10/release-notes.html) (in beta). KSM is a generic OSBAPI service broker that can be integrated with any Helm chart and we do provide [a chart to deploy a RabbitMQ instance](https://github.com/rabbitmq/cluster-operator/tree/master/charts/rabbitmq). The high-level steps required are:
1. Deploy KSM
2. Deploy RabbitMQ Operator to a Kubernetes cluster
3. [Add a service offering to KSM](https://docs.pivotal.io/ksm/0-10/using.html#add)

The overall process is a bit cumbersome right now but we are happy to help with the setup. It should also get easier in the future as we want to [improve our installation process](https://github.com/rabbitmq/cluster-operator/issues/228)

**Comment by ChunyiLyu** [comment]
Hi @aegershman, thanks for sharing your thoughts. Let us know if you have any additional feedbacks on this subject. If not, I will close this issue in 3 days since it's stale.

**Comment by aegershman** [comment]
Sounds good, we'll just go ahead and close it now. Thanks @ChunyiLyu , thanks @mkuratczyk 👍
