### ISSUE TITLE
Failed to bind volumes: provisioning failed for PVC

### ISSUE THREAD

**Issue by vmasule** [rabbitmq/cluster-operator#249]
Hi,

We have a policy to always create encrypted volumes, looks like this volume by default don't create encrypted volume, which is okay,but is there a way or config parameter for enabling encryption on ebs volume with default KMS key or passing KMS_KEY_ID, to force this operator to always create encrypted voumes.

We are testing features of this operator on AWS EKS Cluster and go stuck at creating a volume as Pod creating is failing because of this.

**Comment by mkuratczyk** [comment]
Hi,

As far as I can tell, EKS encryption should be configured on the storageClass level. If so, then in RabbitMQ you just have to use the right storageClass and we do have have a property for that: https://www.rabbitmq.com/kubernetes/operator/using-operator.html#persistence.

If that doesn't answer your question, please provide the YAML you'd expect the Operator to generate (an example of how you configure RabbitMQ to use encrypted volumes manually) and the logs/`kubectl describe` from a failing pod.

**Comment by vmasule** [comment]
Yes, This worked thanks.
