### ISSUE TITLE
Update RabbitMQ version to 3.8.7

### ISSUE THREAD

**Issue by MirahImage** [rabbitmq/cluster-operator#273]
**Is your feature request related to a problem? Please describe.**
The current RabbitMQ version is 3.8.7, which includes a number of bug fixes from 3.8.5, including fixes around federation. I would like to be able to run the latest RabbitMQ version in my clusters.

**Describe the solution you'd like**
Bump the RabbitMQ image to version 3.8.7

**Comment by ChunyiLyu** [comment]
Closing this issue in favor of: https://github.com/rabbitmq/cluster-operator/issues/319
