### ISSUE TITLE
System Requirements for an Upgrade

### ISSUE THREAD

**Issue by chewymeister** [rabbitmq/cluster-operator#28]
**Is your feature request related to a problem? Please describe.**

Due to the variety of use cases different users can have for RabbitMQ, it is important for us to understand the trade off in requirements of the common use cases for our customers. This will inform us what kind of guarantees we need to ensure when performing an upgrade. We have done some work towards making some of these guarantees. This issue is going to be used to help us keep track of the current state of affairs, and help inform us of what needs to be done next.

**Describe the solution you'd like**
I would like for us to achieve the following:
- Remaining steps in order to satisfy minimum requirements for upgrades for GA
- Road map for how to achieve higher levels of upgrade requirements.

**Additional context**
Here is the current state (to be improved) of our system requirements for performing an upgrade.

## Control Plane
**Timeline**
No internal upgradeability claims - yes
Internal upgradeability claims - ?
External upgradeability claims beta- no
External upgradeability claims GA - no

## Behaviours of Aspects of the system
**Data loss**
The control plane (Controller and CRD) is dependent on state that is stored in Kubernetes. This is not our responsibility. If the Kubernetes datastore (etcd) experiences data loss, then we lose the metadata for our CRs. The solution to this would be a restore of a previously made backup of etcd.

**Consistency**
Custom Resource metadata
Although we do not currently have an upgrade workflow, we do know that we will need to migrate properties of the CR between different versions. Without this, we could risk losing properties that have been set by the user if a user were to simply change the API version number of their custom resource.

**Availability**
Currently our controller-runtime is configured to activate leader election for simple active/passive HA. However, we only run one replica of our manager. This means that we do not have a highly available controller.

**Repeatability** (no surprises, partition tolerance, etc)
N/A - we do not have an upgrade workflow

**Performance degradation**
TODO

**Usability** (manual steps, bulk and single-instance upgrades, maintenance windows, etc)
N/A - we do not have an upgrade workflow

## Data plane
**Timeline**
No internal upgradeability claims - yes
Internal upgradeability claims - ?
External upgradeability claims beta- no
External upgradeability claims GA - no
Current state for each aspect of the system

**Data loss**
We are currently running an experiment to see if we experience any data loss with our current default configurations - https://github.com/pivotal/rabbitmq-for-kubernetes/projects/2#card-33229926

**Consistency**
RabbitMQ can be configured to maximise data consistency. We can only control certain aspects of RabbitMQ to ensure data consistency. Customers have to configure their RabbitMQ resources (exchanges, queues and messages e.t.c) to also minimize data loss in order for our mitigations of data loss to take effect.

We now have a `preStop` container hook that will run `rabbitmq-queues check_if_node_is_quorum_critical` and `rabbitmq-queues check_if_node_is_quorum_critical`. This ensures that all distributed queues will have a chance to tell us if they are in a bad state (i.e. unsynchronised) before any RabbitMQ server nodes are taken down for maintenance, thereby keeping the data consistent.

**Note**: 
This only helps us in the situation of a voluntary shutdown. The default value for ‘ha-promote-on-shutdown’ is ‘when-synced. However, the default value for ‘ha-promote-on-failure’ is ‘always’ and can lead to data loss as the view here is availability over consistency. We will need to have a “plan” that allows us to change this to ‘when-synced’ if we want to make consistency a higher priority.
This does mean that maintenance times could potentially last a bit longer as we wait for queues to be synchronised which users may not like (given the frequency that Pod rollout could occur).

**Availability**
RabbitMQ can be configured to maximise data availability. Customers have to configure their RabbitMQ resources (exchanges, queues and messages e.t.c) to sacrifice data consistency for data availability.

We now have a `preStop` container hook that will run `rabbitmq-queues check_if_node_is_quorum_critical` and `rabbitmq-queues check_if_node_is_quorum_critical`. This ensures that all distributed queues will have a chance to synchronise before any RabbitMQ server nodes are taken down for maintenance, thereby ensuring that if a node goes down that hosted the leader of the queue, high availability is still maintained because a new leader can be elected quickly.

**Repeatability** (no surprises, partition tolerance, etc)
N/A - we do not have an upgrade workflow

**Performance degradation**
N/A

**Usability** (manual steps, bulk and single-instance upgrades, maintenance windows, etc)
N/A - we do not have an upgrade workflow

**Comment by coro** [comment]
Stale issue - closing. Covered by other upgrade Issues.
