### ISSUE TITLE
Dependabot should ping to minor versions of certain dependencies

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#286]
## Describe the bug
Dependabot shouldn't check:

* k8s.io/client-go
* k8s.io/api
* k8s.io/api-machinery
* go-logr/logr 

[controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) has both the api and client-go as its dependency. We should update:
* k8s.io/client-go
* k8s.io/api
* k8s.io/api-machinery
* go-logr/logr 

as part of updating controller-runtime, not independently.

We can ping to minor versions for these dependencies for now.

**Comment by MirahImage** [comment]
What versions of client-go, api, and api-machinery should we pin to? Do we feel comfortable bumping to 0.18.* now that we have resolved #230 ?

This would let us bump controller-runtime

**Comment by ChunyiLyu** [comment]
@MirahImage could you ping to the current versions first? We have not tested the new controller-runtime version yet. I would rather bump controller-runtime and its dependencies at the same time, instead of bumping them separately.

**Comment by MirahImage** [comment]
Actually, it appears we can't pin to minors with dependabot, it only allows us to add dependencies to an ignore list, so we will do that and handle bumping these dependencies manually.
