### ISSUE TITLE
Respect ports in additional config

### ISSUE THREAD

**Issue by ansd** [rabbitmq/cluster-operator#294]
Port numbers in the service object are currently hard coded to their defaults.
For example, the AMQP port is [hardcoded](https://github.com/rabbitmq/cluster-operator/blob/a5b93a448cf5ae93b082fa24312c22c227cbed32/internal/resource/client_service.go#L115) to its default 5672.

This is an issue when the user provides a different port number in the [additional config](https://github.com/rabbitmq/cluster-operator/blob/a5b93a448cf5ae93b082fa24312c22c227cbed32/api/v1beta1/rabbitmqcluster_types.go#L254) (e.g. by setting `listeners.tcp.1` to override the AMQP port or setting `mqtt.listeners.tcp.default` to override the MQTT port).

As discussed in https://github.com/rabbitmq/cluster-operator/pull/292#discussion_r478462942, the port shouldn't be hardcoded. Instead, the config should be checked first, and if no port is set, take the default port. If the port is set (and the plugin is enabled), take the port from the config.

This enables us to easily expose [MQTT-over-WebSockets](https://www.rabbitmq.com/web-mqtt.html) and [STOMP-over-WebSockets](https://www.rabbitmq.com/web-stomp.html) when these plugins are enabled (similarly as done in #292 where MQTT and STOMP were exposed).

**Comment by ChunyiLyu** [comment]
The point of override is to provide flexibility in our CRD for any uncommon use cases that we don't foresee. If someone were to override a plugin related port like STOMP, or AMQP, I assume that they know their use cases and know that they need to use both the sts override and the client service override. If we continue to see customizing certain ports as a common pattern across users, we can optimize the workflow (we can even add a top level crd spec field, and people don't even need to bother with the config file)

I propose that we only pick up this issue once we are sure that this is a popular use case.

**Comment by ansd** [comment]
Good point @ChunyiLyu, let's wait to see whether this is a common use case or whether users override the port and forget the sts override before implementing this one.

I close this isssue for now. We can re-open it when necessary.
