### ISSUE TITLE
Chart/operator/templates/CRD.yaml is missing 'override' when compared with Config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml

### ISSUE THREAD

**Issue by ankursoni** [rabbitmq/cluster-operator#295]
Chart/operator/templates/CRD.yaml is missing 'override' section which is very well present in Config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml

**Comment by ChunyiLyu** [comment]
Hi @ankursoni thanks for raising this bug. The team has made the decision of deleting the operator helm chart (we will keep the rabbitmqcluster chart for now), and it should now be deleted in the main branch. I will close this issue for now.

**Comment by ankursoni** [comment]
But why would you do delete operator helm chart?
Please think in the broader perspective of automation where the devops engineers are trying to install operator using flux helm release operator which makes it so easy to automatically install the operator from this git repository without having to clone and do manual steps!

**Comment by mkuratczyk** [comment]
At this point helm adds maintenance overhead (we had to keep helm templates in sync which led to issues like this one). Additionally Helm doesn't support CRD upgrades that we are working on (see https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations).

As for the installation process - we are working on making the operator installation easier - it will be a single `kubectl` command and will not require cloning the repository so you will get the same convenience without helm soon.

Last thing, current installation steps, while not ideal, can be performed as a single command. You can download [kubectl-rabbitmq plugin](https://github.com/rabbitmq/cluster-operator/blob/main/bin/kubectl-rabbitmq), put it on your PATH and then you can do `kubectl rabbitmq install-cluster-operator`.
