### ISSUE TITLE
controller-gen: Bump and use go tools

### ISSUE THREAD

**Issue by ansd** [rabbitmq/cluster-operator#306]
Currently, the controller-gen version is hard-coded in https://github.com/rabbitmq/cluster-operator/blob/458514b5f8063b2586efc6f87ab2881d691c576f/Makefile#L145

This issue is about:
1. Bump controller-gen to latest
2. Use the [go tools approach](https://marcofranssen.nl/manage-go-tools-via-go-modules/).
This has two advantages. The first advantage is that in future, we won't need to manually bump the controller-gen version anymore. Depandabot will do it. The second advantage is that we will all use the same `controller-gen` version when developing on our workstations.
3. Include kustomize in the `tools.go` file.

**Comment by IlyaAlexin** [comment]
May I take this issue?

**Comment by ansd** [comment]
@IlyaAlexin yes please, try it out and let me know if you have any questions 🙂

**Comment by IlyaAlexin** [comment]
Hi @ansd,
I have implemented the solution as it was suggested in the article.
I have a few issues/questions:

- After **make controller-gen** I had a couple of automatic changes in both go.mod and go.sum files. Should I add them in my pull request?

- Unit & integration tests pass but my local system-tests fail for both main and my feature branch. Can you help me to fix system tests if my errors are typical? Screenshot is below:
![image](https://user-images.githubusercontent.com/48867156/92635204-1bb91f80-f2de-11ea-99ea-73223c7f39a0.png)

**Comment by ansd** [comment]
Awesome, thank you @IlyaAlexin 🙂

Yes, please also commit the changes of the go.mod and go.sum files. Having the tools versions committed in the go.mod file makes sure that we are all using the same versions of the tools.

Don't worry about the system-tests for now since the failing system tests are not related to your changes.
