### ISSUE TITLE
Consider moving rabbitmq_prometheus to the list of additional (optional) plugins

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/cluster-operator#316]
Originally requested in https://github.com/rabbitmq/cluster-operator/issues/309 by @timbrd.

Currently the list of required plugin includes

 * `rabbitmq_peer_discovery_k8s` for peer discovery
 * `rabbitmq_prometheus`
 * `rabbitmq_management` for management UI and HTTP API

we can move `rabbitmq_prometheus` to the [additional plugin list](https://github.com/rabbitmq/cluster-operator/blob/main/internal/resource/rabbitmq_plugins.go#L23) which can be overridden by the user. Then it would
still be enabled by default but won't be forced. The same can be considered for the management plugin.

There are no plans to make it possible to disable Kubernetes-specific peer discovery as in most cases, this would be the most convenient option and there are no reasons to switch to an alternative mechanism.

Per discussion with @mkuratczyk.

**Comment by gerhard** [comment]
As long as we don't allow Tanzu RabbitMQ users to disable rabbitmq_prometheus, I have no qualms with this change.

Going forward, we should not be expected to support RabbitMQ deployments that don't have metrics.

**Comment by michaelklishin** [comment]
I completely agree.

**Comment by ChunyiLyu** [comment]
I'm not sure whether making these two plugins possible to disable is something we should do. For the prometheus plugins, enabling it is crucial for people to get support from the team. And the management plugin is widely popular and may help diagnosing support issues as well. I think these plugins are crucial to general functionalities of rabbit and should always be enabled. 

Adding the two plugins to the list of additional ones makes it easy for people to disable them. All users have to do is pasting over the section of `spec.rabbitmq.additionalPluigins` in their rabbit manifests. I'm not convinced that the flexibility benefits here outweighs supportability. Thoughts?

**Comment by michaelklishin** [comment]
We could not reproduce the resource usage in #309 so I'm happy to close it since now three members of our team are skeptical about this idea.
