### ISSUE TITLE
Support import definitions workflow better

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#321]
**Is your feature request related to a problem? Please describe.**
If users import definitions through statefulSet override, admin credentials will be set from the imported configuration. However, a generated secret object still exists for this cluster, and will not contain the updated credential from the definitions json, but an auto generated one. So yes you can configure admin credential using override, but you will get a secret object with wrong content, and that's confusing to users. We should add better support for this use case.

**Describe the solution you'd like**
1. We can stop creating the secret object if users are importing definitions at cluster start.
2. We can update the content of the secret object with the imported definitions.

**Describe alternatives you've considered**

**Additional context**

**Comment by Zerpet** [comment]
**Context**

I've been thinking about this issue and how we can improve this workflow. The main challenge at the moment is to determine, from the Operator perspective, that "we are importing definitions". For a human, this is as straightforward as "the property `load_definitions` property is set in `rabbitmq.conf`". For the Operator, inferring the `rabbitmq.conf` is not so straightforward; we could string match `load_definitions` if `spec.additionalConfig` is set, but I have two arguments against: (1) string matching is error prone and (2) we make a hard assumption that `load_definitions` is the right key i.e. if this key changes in the future, we will break. One could argue that `load_definitions` key is unlikely to change, but that doesn't change the fact that we are relying on an external factor/system to function correctly.

Given these two challenges, I think we should consider making this feature "top level". Making this top level solves the problem of determining whether "we are importing definitions". Then we can skip the creation of the Admin Secret (or Default Secret). The Status field for the admin Secret should be `nil` in this case. The field is a pointer in the code, therefore it is expected to be nil in some situations i.e. this won't be a breaking change.

I'm against inferring the imported definitions for an "admin user" to populate the status field for the same reason as (1) string matching is error prone and we are assuming there is an admin user.

**Examples supporting (1)**

These examples don't mean to be a blocker, but to showcase some edge cases that make string matching an unreliable method.

```yaml
[...]
spec:
  rabbitmq:
    additionalConfig: |
      # perhaps use load_defitions ?
      default_user = foo
      default_pass = bar
```

```yaml
[...]
spec:
  rabbitmq:
    additionalConfig: |
      management.ssl.ca_cert = /my/path/load_definitions/ca.crt
```

**Comment by Zerpet** [comment]
### Context

I've been considering implementing this by parsing the `.spec.rabbitmq.additionalConfig` using the Go Ini library and determine "are we importing definitions?" based on the presence of the key `load_definitions`; in such case, I would advocate to skip the creation of the Admin Secret (or Default User Secret). Initially this felt like a behaviour change, which would be considered a breaking change. However, looking at the [compatibility guidelines](https://github.com/kubernetes/community/blob/058afb16fc23f3a24948a56211dc0220e48952a1/contributors/devel/sig-architecture/api_changes.md#on-compatibility), we are not changing the behaviour and prior versions of the Operator will continue to work, regardless of the work done here.

Depends how much we want to automate this use case, we have two options:

- Add logic to parse the `additionalConfig` field using the Go Ini library and skip Admin Secret creation if the key `load_definitions` is present.
- Add a high level property of type `LocalObjectReference`, which will be expected to be a ConfigMap with key `definitions.json`. Implement logic in the Operator to mount this file and configure `load_definitions` in `rabbitmq.conf`. In this case, the Admin Secret won't be created.

Important to note that the first option would not change the fact that a user needs to use the StatefulSet override feature to mount the definitions into the container.
