### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by edbyford** [rabbitmq/cluster-operator#324]

**Comment by RichiCoder1** [comment]
Is rolling upgrades something that made it into 1.0.0, or is that still an at-a-later date epic?

**Comment by mkuratczyk** [comment]
Yes, changing the RabbitMQ image/version should work and we won't ship breaking changes to the operator without notice (we made some in 0.49 to avoid them later)

**Comment by RichiCoder1** [comment]
Belated but worth noting the official docs still say this isn't supported
