### ISSUE TITLE
Create CRD Version Upgrade KEP

### ISSUE THREAD

**Issue by chewymeister** [rabbitmq/cluster-operator#33]
**Is your feature request related to a problem? Please describe.**
We do not currently have a solidified work flow for upgrading from CRD version A to B. We do not know what happens when multiple versions of an API need to transition to and from each other.

We need a place to discuss both the problems and solutions for upgrading CRDs.

**Describe the solution you'd like**
We should use a KEP to help collaborate efforts to explore problems and solutions related to upgrading the operator.

This issue can be closed when:
- we have a first pass completed document (filling in required fields)
- the document contains the current state of upgrading an operator contained in [this issue](https://github.com/pivotal/rabbitmq-for-kubernetes/issues/28)

Progress
- [ ] create issue for 'storage version'
- [ ] what happens when you get an old version using a newer version that is set as current
- [ ] what does k8s version priority mean
- [ ] prototype the multi version kubebuilder example to understand how multi version works
  - [ ] what happens when you update CRD with new version and update controller at the same time, or in different steps
  - [ ] what does it mean for a CR to be upgraded? Does it simply need to have the `apiVersion` 
value changed to the new version?
  - [x] is there a deep copy function we can use to copy properties from source version to destination version in the conversion function? - Yes there is, but we cannot use it to set of version A to be the spec of version B. This means each individual property value has to be copied manually line by line.
- [ ] write proposal section for KEP
- [ ] write solution section for KEP

**Comment by ChunyiLyu** [comment]
Closing stale issue.
