### ISSUE TITLE
Repo still refers to old Docker image in places

### ISSUE THREAD

**Issue by coro** [rabbitmq/cluster-operator#338]
## Describe the bug
The repo references the old Docker image `rabbitmqoperator/rabbitmq-cluster-kubernetes-operator-dev` and `rabbitmqoperator/rabbitmq-cluster-kubernetes-operator` in places, which were replaced by `rabbitmqoperator/cluster-operator-dev` and `rabbitmqoperator/cluster-operator`, respectively.

**Expected behavior**
I would expect both of these image names to be replaced with the new image name. It would be worth investigating where in our repo & tooling the old image is referenced, then updating to the new image name.

## Additional context

Once these deletions are made, we can remove the old images from Dockerhub.

**Comment by ChunyiLyu** [comment]
Remember to update this file as it uses the docker image as a placeholder string when using `kustomize edit image`: https://github.com/pivotal/rabbitmq-for-kubernetes-ci/blob/master/tasks/operator-system-tests/task.yml

**Comment by Zerpet** [comment]
After https://github.com/pivotal/rabbitmq-for-kubernetes-ci/commit/a0a8cd994494048873add181f82390934bcab46e, this issue can be closed.
