### ISSUE TITLE
Investigate our coupling to RabbitMQ Community docker entry point script

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#340]
## Problem statement

We rely on some behaviour implemented in [RabbitMQ Community](https://hub.docker.com/_/rabbitmq) Docker [entry point script](https://github.com/docker-library/rabbitmq/blob/66ddebbb7fc778c481da06856e350ceae3e02113/3.8/ubuntu/docker-entrypoint.sh). One example is the templating of the default username and password via environment variables e.g. `RABBITMQ_DEFAULT_PASS_FILE`. By relying on this script, we (and any user) are unable to switch to a different RabbitMQ docker image.

## Expected outcome

In this issue we will track the investigation to determine how much and on what points we rely on the docker entry point script, and propose changes to address this coupling. If the changes required are small enough, they can be implemented as part of this issue.

**Comment by gerhard** [comment]
FWIW, the Docker entry point script will be going away: https://github.com/docker-library/rabbitmq/pull/424

[This is how we handle the default user in the "other" RabbitMQ Docker image](https://github.com/rabbitmq/infrastructure/blob/master/commercial-edition/docker/rmq/default_user.conf). There is a [related TODO](https://github.com/rabbitmq/infrastructure/commit/c9cd2d382f59ac73d4dbeaeb777452458b532098#diff-53cb85b79278630e8a6eefd00e690f0fR149-R150) which @coro just reminded me to follow-up on. Thanks 👍🏻

**Comment by coro** [comment]
I've investigated the entrypoint script, and the only behaviour we rely on from it is the default user/password configuration. It should be fairly simple to transition this to a mounted configMap/`.conf` file, and so I'll do this as part of this issue.

**Comment by gerhard** [comment]
It would be great for the public RabbitMQ Docker image to have the same behaviour. Is this potential PR to https://github.com/docker-library/rabbitmq/ in scope?

For more context, read why now is a great time to start breaking down docker-entrypoint.sh functionality into sysctl config fragments: https://github.com/docker-library/rabbitmq/pull/422#issuecomment-650074731

A separate but somewhat related functionality that will require a different approach to using env vars in the Docker image: https://github.com/rabbitmq/rabbitmq-cli/issues/443. Hint: `--erlang-cookie`

cc @tianon @michaelklishin

**Comment by Zerpet** [comment]
The PR for this issue will very likely be specific to the Operator and Kubernetes. That doesn't mean that we can't consider a contribution to the public RabbitMQ Docker image with our learning from this issue 😄

**Comment by coro** [comment]
> The PR for this issue will very likely be specific to the Operator and Kubernetes. That doesn't mean that we can't consider a contribution to the public RabbitMQ Docker image with our learning from this issue 😄

On it: https://github.com/docker-library/rabbitmq/pull/440

Tried to keep it as consistent as possible across the two repos (i.e. credentials in `/etc/rabbitmq/conf.d/default_user.conf`, as is the case in the commercial RMQ image)
