### ISSUE TITLE
Inconsistent mapping of imagePullSecret to corev1 API type

### ISSUE THREAD

**Issue by coro** [rabbitmq/cluster-operator#343]
## Describe the bug
Many fields in the RabbitmqCluster CR spec map directly to lower-level primitive spec fields with the same field name. For example:

`rabbitmq.com/v1beta1.RabbitmqClusterSpec.Replicas` -> `v1.StatefulSetSpec.Replicas`
`rabbitmq.com/v1beta1.RabbitmqClusterSpec.Image` -> `v1.Container.Image`
`rabbitmq.com/v1beta1.RabbitmqClusterSpec.Resources` -> `v1.Container.Resources`
`rabbitmq.com/v1beta1.RabbitmqClusterSpec.Affinity` -> `v1.PodSpec.Affinity`
`rabbitmq.com/v1beta1.RabbitmqClusterSpec.Toleration` -> `v1.PodSpec.Toleration`

There is one inconsistency in this 1-1 mapping:
`rabbitmq.com/v1beta1.RabbitmqClusterSpec.ImagePullSecret` (string) -> `v1.PodSpec.ImagePullSecrets[0]` ([]string[0])

The Image Pull Secret in the CR spec is treated as a single string rather than a list of secrets, and is inserted as the only element in the list of Image Pull Secrets in the RabbitMQ pod.

The Pod spec allows for multiple secrets per pod, to allow for, for example, different private repositories for each of a main container and sidecar container in a pod.

The naming & typing inconsistency between our API's `imagePullSecret` and the core API's `imagePullSecrets` is confusing to users. We should change our API to be consistent with the underlying core API.

## To Reproduce
Assuming there is a Docker authentication secret created [as per the documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials) called `regcred`; attempting to create a `rabbitmq.com/v1beta1.RabbitmqCluster` containing the following snippet fails:

```yaml
spec:
  image: <SOME PRIVATE IMAGE>
  imagePullSecrets:
  - regcred
```
Error:
```
rabbitmqclusters.rabbitmq.com "rabbitmqcluster-sample" was not valid:
* : Invalid value: "The edited file failed validation": ValidationError(RabbitmqCluster.spec): unknown field "imagePullSecrets" in com.rabbitmq.v1beta1.RabbitmqCluster.spec
```
Works if the user uses the following:
```yaml
spec:
  image: <SOME PRIVATE IMAGE>
  imagePullSecret: regcred
```

**Expected behavior**
Expected the core v1 API to work on the CR API.

## Version information
- RabbitMQ Cluster Operator: 0.37.0
- Kubernetes: 1.18.2
 
## Additional context
Removing this field is a breaking API change and has consequences for consumers. Consult the [Kubernetes Deprecation Policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/) to find out what we're permitted to do with our API version.

**Comment by mkuratczyk** [comment]
I think we could use this issue to practice version migration. Until now we'd just change the CRD without bumping the version but this is exactly the kind of change that should be introduced in a new version.
