### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#354]
### Problem statement

We are releasing a new version of the Operator on every commit or PR that makes it to `main` branch. Sometimes we make changes that do not deliver a new feature or fix a bug e.g. change to make file, changes to manifests. Releasing on every commit is tagging almost every commit on `main`, which seems unnecessary. This also adds complexity to the task of determining the difference between two version e.g. 0.30.0 vs 0.40.0. There are multiple versions in between these two and it's not clear at a glance what has changed; determining the diffrences requires scanning through all intermediate versions.

### Describe the solution you'd like

Stop releasing on every commit and make this action an arbitrary decision. The release process is automatic and the decision of generating this release will be arbitrary.

**Comment by mkuratczyk** [comment]
For the time being I'd suggest adding `[skip ci]` to the commit message for non-code changes (haven't tried but it likely works and if not - can easily be enabled). Releasing on every code change is ok at this stage in my opinion.

**Comment by mkuratczyk** [comment]
After playing with `ci skip` and `commit_filter.include`/`commit_filter.exclude` which were surprisingly confusing and/or hard to implement, I just changed the release job to require a manual trigger. Let's see how that works for us and we can add a nightly build or something else later.
