### ISSUE TITLE
Multiarch image with ARM64 support

### ISSUE THREAD

**Issue by elmariofredo** [rabbitmq/cluster-operator#366]
**Is your feature request related to a problem? Please describe.**

Unable to run on Raspberry PI K8s cluster

**Describe the solution you'd like**

Multiarch support same as official rabbitmq image has but mainly `linux/arm64/v8`

**Comment by mkuratczyk** [comment]
Hi. Thanks for the interest in the operator and ARM support. We would be happy to run such a build in our CI system and publish ARM images but since it's not a top priority for us right now, it would be great if you could submit a PR with the necessary changes. A new `make docker-build-arm64` target or something like that. Thank you.

**Comment by Gsantomaggio** [comment]
I deployed the rabbitmq-operator on my (old) Raspberry `arm32 v7` just changed on the docker image:

```
RUN CGO_ENABLED=0  GOARCH=arm GOARM=7 GO111MODULE=on go build -a  -o manager main.go
```
@elmariofredo  in your case will be:

```
RUN CGO_ENABLED=0  GOARCH=ARMv8  GO111MODULE=on go build -a  -o manager main.go
```

then build the docker image:
```
docker build -t rabbitmq-operator-armv8  . 
```

**Comment by zackkitzmiller** [comment]
@Gsantomaggio where did you make that change? I'd be interested in making this a more complete fix for a PR, but I'm not sure where you actually made the change.

**Comment by Gsantomaggio** [comment]
Hi @zackkitzmiller thank you for looking on it.

I changed the  [docker file](https://github.com/rabbitmq/cluster-operator/blob/main/Dockerfile#L18)

I would implement something like:
```
docker-build-%
```

with different options like:
```
amd64
arm32
arm64
```

**Comment by zackkitzmiller** [comment]
Yeah - that's where I headed. I haven't done a lot of operator development, so I was looking for a starting point! Thank you. I'll try to abstract this out and see what can come of it. 

Thanks!

**Comment by eorl-0314** [comment]
@zackkitzmiller Any update on this ?

**Comment by onetonfoot** [comment]
As a temporary workaround, you can get it running, by cloning this repo and editing the `Dockerfile`

```
RUN CGO_ENABLED=0  GOOS=linux GOARCH=arm64 GO111MODULE=on go build -a  -o manager main.go
```

Then build and push the `Dockerfile` to some repo. Finally update the image for the deployment with

```
kubectl set image -n rabbitmq-system deploy/rabbitmq-cluster-operator operator=<NAME OF IMAGE>
```

**Comment by DiademShoukralla** [comment]
Hello! Is there any update on this? I am currently attempting the temporary workaround mentioned above, but I was wondering if there's going to be a permanent fix. Specifically , I am unable to run the Cluster Operator on my Oracle Cloud cluster with linux/arm64 nodes (VM.Standard.A1.Flex). Thanks in advanced!

**Comment by wojtek-viirtue** [comment]
+1 on this.  Couldn't use the bitnami helm charts so I ended up here.  Arm64 is going to become more and more popular with the new mac book pros.  At least there's a workaround for now.  Thank you!

**Comment by soapiestwaffles** [comment]
+1 also. couldn't use out-of-the-box since all we run is arm-based clusters.

**Comment by tlmcphillips** [comment]
+1 As well!

**Comment by mohsinonxrm** [comment]
BTW, if anyone wants to pull from docker, I've just built the images for ARM64. Although, wouldn't recommend using those in PRD environment as I'm not providing any support. Use these for purely experimentation and learning purposes.

Cluster Operator:
https://hub.docker.com/repository/docker/mohsinonxrm/rabbitmq-cluster-operator

Messaging Topology Operator:
https://hub.docker.com/repository/docker/mohsinonxrm/rabbitmq-messaging-topology-operator

I believe if you deploy using bitnami's helm chart, you can specify the images.

anyway, you can certainly build the images yourself as well with the above mentioned instructions.

**Comment by yankay** [comment]
+1
