### ISSUE TITLE
Add verify_none configuration option for tls

### ISSUE THREAD

**Issue by data-dude** [rabbitmq/cluster-operator#374]
I didn't see a way to configure the operator so that tls is set to verify_none.

**Comment by mkuratczyk** [comment]
RabbitMQ configuration properties can be provided through `spec.rabbitmq.additionalConfig` property of `RabbitmqCluster` like in this example:
https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/custom-configuration/rabbitmq.yaml

Is this what you are looking for?

**Comment by data-dude** [comment]
yea that's it.  Thanks!  You can close this.
