### ISSUE TITLE
Label RMQ pods with the like of created_by_operator_version_[version]

### ISSUE THREAD

**Issue by yaronp68** [rabbitmq/cluster-operator#406]
**Is your feature request related to a problem? Please describe.**

_As a user I would like to know which operator version created my pod so that I can understand what configuration options were available and when if this pod needs an upgrade_
When a user want to manage the rabbit pods it owns especially in the context of upgrade it is good to know which pods were created by the operator and the version of the operator (which can give an indication about the configuration features 
available during creation etc). This might useful for upgrade pods scenario

**Describe the solution you'd like**

Operator should add a label to the pod indicating that it was created by operator version X

**Describe alternatives you've considered**

**Additional context**

**Comment by mkuratczyk** [comment]
Do mean original creation or should this label be updated after an upgrade, when a newer version of the operator reconciles this instance?

**Comment by yaronp68** [comment]
I think that it should be the creator version. When we upgrade the operator we would probably want to eventually upgrade or renew the instances (as a good practice a POD should not live long: CVEs, features, etc)
