### ISSUE TITLE
Install RabbitMQ using this operator via arkade

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/cluster-operator#411]
What are your thoughts on having `arkade install rabbitmq` install the operator if it's missing, then deploy the default RabbitmqCluster that the operator deploys?

https://github.com/alexellis/arkade#explore-the-apps

**Comment by mkuratczyk** [comment]
I haven't heard about `arkade` until now so no strong opinions. I'd be interested in hearing from the community if they use `arkade`.

**Comment by gerhard** [comment]
Sure thing! Please ask around and see what they say 😉
