### ISSUE TITLE
Set `disk_free_limit.absolute = 2GB` by default

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#412]
The default is 50MB which is not suitable even for development environments. In the production example we can set it differently (https://github.com/rabbitmq/cluster-operator/pull/401suggests relative=1.0). Given we provision 10GB volume by default, 2GB disk free sounds reasonable.

**Comment by MirahImage** [comment]
This seems slightly non-trivial, in that, to avoid conflicting limits, we need to detect if a user sets a disk_free_limit (either relative or absolute), and only set a limit if the user has not already configured a limit.

**Comment by mkuratczyk** [comment]
Not necessarily. RMQ allows the same property to appear multiple times in the config file and the last value wins. So if we always add it and then append `additionalConfig` (that we do), user can override our value.

**Comment by MirahImage** [comment]
Ah, right, thank you. I had forgotten that bit of context.
