### ISSUE TITLE
How to reliably access Management GUI?

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#417]
Currently we treat the Management port just like all other ports. That means there are two ways access it:
1. When using `LoadBalancer` as the service type
2. When port-forwarding is manually set up

The former may be tricky - not all deployments can provision LoadBalancers, some will provision LBs with public IPs that the Management GUI/API probably shouldn't be exposed with, etc.
The latter only allows forwarding to a specific pod and therefore makes it hard to monitor RabbitMQ during upgrades for example.

Is there something we can do to make it easier to access Management GUI/API in a reliable but secure way?

**Comment by Zerpet** [comment]
If the user accessing the Management UI does not have direct line of sight, they will have to ideate some workarund like port forwarding. I can't think of a way to ease this challenge from the application a.k.a. Cluster Operator side.

If the concern is with exposing RabbitMQ through a public IP, a potential solution would be to use a secure NGINX Ingress. Another potential solution is to use [Contour](https://projectcontour.io/) to provide secure ingress access and off-load the responsibility of provisioning a secure ingress.

**Comment by mkuratczyk** [comment]
The best I've found so far:
```
kubectl run rmq-mgmt-proxy --image=alpine/socat --port=15672 tcp-listen:15672,fork,reuseaddr tcp-connect:MYRMQ-rabbitmq-client:15672
kubectl port-forward rmq-mgmt-proxy 15672
```

With these two commands, connections to `http://localhost:15672` are properly (or at least decently) load balanced between RabbitMQ nodes. You can check `http://localhost:15672/api/overview` to see which node you are connected to, kill that pod and refresh the page - it should work immediately by simply forwarding to a different node.

It's far from perfect but I think I'll add that to `kubectl-rabbitmq` until we have a better option.

**Comment by mkuratczyk** [comment]
One more option is to create an additional service specifically for the Management port(s). Different rules could be applied to it since Management is often accessed from a different network for example. We've discussed potentially splitting Management from the service created by the Operator in the future.
