### ISSUE TITLE
Policy provisioning

### ISSUE THREAD

**Issue by EugenFo** [rabbitmq/cluster-operator#439]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to add or update policies manually or via API(or I missed some docs here). It would be a greate feature if the operator would automatically provision the rabbitmq cluster with defined policies.

**Describe the solution you'd like**
After the operator creates the rabbitmq cluster he should automatically add policies that where defined in the RabbitmqCluster yaml. 

**Describe alternatives you've considered**
Alternatives are doing it manually or via rest calls.

I hope it's possible to do so. Thanks!

**Comment by Zerpet** [comment]
Hello @EugenFo 👋 
We are considering adding support for various RabbitMQ primitives e.g. users, queues, vhosts, etc. via additional CRDs. Adding a field to `RabbitmqCluster` spec is a potential solution, although we would like to decouple the `RabbitmqCluster` resource from RabbitMQ primitives. We have not started working on this concept yet, as we are working on making the current API stable. We will track progress of "RabbitMQ primitives" work in #12. For now, the alternative, as you mentioned, is to provision policies via REST calls (or manually).

**Comment by EugenFo** [comment]
Hey @Zerpet 
Awesome! I will stay tuned for this.
Closing this issue as it is already tracked in #12
