### ISSUE TITLE
Release and test `kubectl-rabbitmq`

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#440]
**Is your feature request related to a problem? Please describe.**

We would like users of rabbitmqcluster to start using the cli tool that we have developed. We would like to test the cli tool, and making sure that it is compatible with the release for usability.

**Describe the solution you'd like**

- `kubectl-rabbitmq version` should return the version of the operator that the cli is tested and released with.
-  cli is tested in the CI
-  cli is released as an artifact in the release

**Describe alternatives you've considered**

**Additional context**

**Comment by ansd** [comment]
Done:
* Add tests https://github.com/rabbitmq/cluster-operator/pull/445
* Run tests in CI https://github.com/rabbitmq/cluster-operator/pull/445
* Release https://github.com/kubernetes-sigs/krew-index/pull/895

Todo:
* Release automation - add GitHub action, see https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/
* Add version command to plugin
