### ISSUE TITLE
Setting labels via metadata.label is incompatible with Flux

### ISSUE THREAD

**Issue by Tolsto** [rabbitmq/cluster-operator#442]
We use Flux for our GitOps (https://github.com/fluxcd/flux2) pipeline. Flux sets a couple of labels for each object/resource under its control. One of it is the current git commit id which changes with every Flux reconciliation that gets triggered by changes in the source repository. Currently, this triggers a restart of all RabbitMQ pods.

I'd propose to set the labels that affect the ReplicaSet/Pods under `spec.template` and not directly under `metadata`.

**Comment by Zerpet** [comment]
Hi @Tolsto 👋 I'm not familiar with Flux, please bear with me if I didn't fully understand your request. My understanding is that you have a YAML for `RabbitmqCluster` in some git repository, Flux watches this repository for changes and reconciles changes. During this reconciliation, Flux will label all the resources from the git repo with the commit ID. This means that the resource `RabbitmqCluster` is relabelled every time Flux reconciles, even if `RabbitmqCluster` itself was not changed. At the moment, this relabelling is causing a cluster restart, which I understand is not very desirable. Ideally, you would like metadata changes to `RabbitmqCluster` resource to not trigger a rolling restart.

Does this understanding describe your situation?

**Comment by Tolsto** [comment]
Yes, you got it.
I also think that nesting the metadata that gets passed on to the actual pods under `spec.template` would be more in line with other well-known Kubernetes resources like `Deployments`

**Comment by Zerpet** [comment]
Hi @Tolsto 👋 We merged a PR #449 to stop updating Pod template labels in the event of a `RabbitmqCluster` update. If the `RabbitmqCluster` is created with a set of labels, those labels won't be present in the StatefulSet `.spec.template.metadata`; those labels will still be present in the other resources created by the Operator e.g. ConfigMap.

Does this change help in your case?

We considered your suggestion of adding a field `.spec.template` to the `RabbitmqCluster` resource, however we are planning to release a stable version soon and we don't want to introduce this change right now. We will consider the inclusion of this change in a future version, as it makes sense to align with the structure of other Kubernetes APIs.

**Comment by Tolsto** [comment]
@Zerpet Yes, it helps. Thank you.
