### ISSUE TITLE
Document recommended production ready configurations

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#453]
**Is your feature request related to a problem? Please describe.**
Our recommended production configurations are documented as an [example manifest](https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/production-ready/rabbitmq.yaml). We should consider having it in a more obvious place so people are aware of the recommendation.

**Describe the solution you'd like**
We can have a new section or a new page in rabbitmq website.

**Describe alternatives you've considered**

**Additional context**

**Comment by Zerpet** [comment]
There is a [production checklist](https://www.rabbitmq.com/production-checklist.html) in RabbitMQ documentation. We could use this opportunity to review the check list, verify it still makes sense and that we don't contradict/recommend something different.

**Comment by Zerpet** [comment]
This issue will be resolved when https://github.com/rabbitmq/rabbitmq-website/pull/1129 is merged

**Comment by Zerpet** [comment]
PR merged, closing this issue.
