### ISSUE TITLE
Operator API for adding RMQ user 

### ISSUE THREAD

**Issue by yaronp68** [rabbitmq/cluster-operator#454]
**Is your feature request related to a problem? Please describe.**
For users that wants to create a cluster and bind it to app consumers / producers via KSM, there's a need to create the RMQ users so that users will not connect to RMQ with the default user
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MirahImage** [comment]
Duplicate of #12

**Comment by MirahImage** [comment]
Closing, as this is now handled by the [messaging topology operator](https://github.com/rabbitmq/messaging-topology-operator).
