### ISSUE TITLE
Document common labels and naming of child resources

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#455]
**Is your feature request related to a problem? Please describe.**
There is no documentation about all resources created by the operator would have three common labels. Those are useful information for our users if they would like to inspect all resources created by the operator, or all resources that belongs to a rabbitmqcluster. We should also document how to name these resources as well. 

**Describe the solution you'd like**
I think it could be a new section in the `using-operator`, or a new page if it makes sense.

**Describe alternatives you've considered**

**Additional context**

**Comment by Zerpet** [comment]
I'm finding uncomfortable to navigate the "Using the Operator" guide. I'm going to use this issue to also add an index to the guide and review the current information.

**Comment by Zerpet** [comment]
Submmited https://github.com/rabbitmq/rabbitmq-website/pull/1092

**Comment by Zerpet** [comment]
PR merged. Closing
