### ISSUE TITLE
Rabbitmq website `Documentation: Table of Contents` should contain links to the kubernetes docs

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#456]
**Is your feature request related to a problem? Please describe.**
I expected to find links our kubernetes docs in https://www.rabbitmq.com/documentation.html but there is none.

**Describe the solution you'd like**
We should have a dedicated section rabbitmq kubernetes cluster operator, which lists all the docs we have:
- install operator 
- using operator
- operator monitoring
- troublingshooting operator
- upgrade operator

Or, it should at least point to the overall page `operator overview`.

**Describe alternatives you've considered**

**Additional context**

**Comment by Zerpet** [comment]
https://github.com/rabbitmq/rabbitmq-website/pull/1086 is merged. Closing this issue.
