### ISSUE TITLE
Impossible to start cluster with 3 replicas after kubernetes nodes reboot

### ISSUE THREAD

**Issue by VasylSamoilov** [rabbitmq/cluster-operator#480]
## Describe the bug
Cluster deployed in EKS 1.17 with 3 replicas. After cluster worker group was terminated and restarted, rabbitmq cluster cannot boot - statefulset not starting up. And there is no option to modify statefulset startup policy or force boot.

## To Reproduce
1. Create cluster with 3 rabbitmq nodes.
2. Terminate kubernetes nodes.
3. Start new kubernetes nodes.
4. Cluster will not be able to recover.

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**
Cluster will recover after node crash.

## Version information
- RabbitMQ: 3.8.9
- RabbitMQ Cluster Operator: rabbitmqoperator/cluster-operator:0.48.0
- Kubernetes: AWS EKS 1.17
 
## Additional context
```
2020-11-19 23:47:14.131 [info] <0.372.0> Starting worker pool 'worker_pool' with 2 processes in it
2020-11-19 23:47:14.131 [info] <0.272.0> Running boot step database defined by app rabbit
2020-11-19 23:47:14.231 [info] <0.272.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2020-11-19 23:47:44.232 [warning] <0.272.0> Error while waiting for Mnesia tables: {timeout_waiting_for_tables,['rabbit@rabbitmq-cluster-rabbitmq-server-2.rabbitmq-cluster-rabbitmq-headless.default','rabbit@rabbitmq-cluster-rabbitmq-server-1.rabbitmq-cluster-rabbitmq-headless.default','rabbit@rabbitmq-cluster-rabbitmq-server-0.rabbitmq-cluster-rabbitmq-headless.default'],[rabbit_durable_queue]}
2020-11-19 23:47:44.232 [info] <0.272.0> Waiting for Mnesia tables for 30000 ms, 8 retries left
2020-11-19 23:48:14.233 [warning] <0.272.0> Error while waiting for Mnesia tables: {timeout_waiting_for_tables,['rabbit@rabbitmq-cluster-rabbitmq-server-2.rabbitmq-cluster-rabbitmq-headless.default','rabbit@rabbitmq-cluster-rabbitmq-server-1.rabbitmq-cluster-rabbitmq-headless.default','rabbit@rabbitmq-cluster-rabbitmq-server-0.rabbitmq-cluster-rabbitmq-headless.default'],[rabbit_durable_queue]}
2020-11-19 23:48:14.233 [info] <0.272.0> Waiting for Mnesia tables for 30000 ms, 7 retries left
```

**Comment by VasylSamoilov** [comment]
Maybe podManagementPolicy: "Parallel" should be set ?

**Comment by mkuratczyk** [comment]
Thanks for reporting this issue - we'll look into that soon. We do have a story to learn more about the behaviour of the `podManagementPolicy: Parallel` (https://github.com/rabbitmq/cluster-operator/issues/298) and the initial findings were promising so we might end up doing that indeed.

**Comment by VasylSamoilov** [comment]
The problem right now that operator is very aggressive and there is no option to change statefulset at all, operator will revert changes immediately. I was trying to do try force_boot but pod is not started, so I can't exec into it, and all options to alter init container failed. Please think how to provide recovery options for failed clusters.

**Comment by mkuratczyk** [comment]
Since we haven't completed #298, I can't guarantee that this is a good idea but you can change the StatefulSet using the [.spec.override.StatefulSet](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#override) property:
```
  apiVersion: rabbitmq.com/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: rabbit
  spec:
    override:
      statefulSet:
        spec:
          podManagementPolicy: Parallel
```

**Comment by VasylSamoilov** [comment]
It wasn't a very good idea to rely on operator without disaster recovery options in the first place, but it is what it is.

**Comment by mkuratczyk** [comment]
Can you explain your last comment please? I showed you how to easily achieve what you suggested. We introduced the `override` property exactly to give flexibility and allow users to customize the deployment.

**Comment by VasylSamoilov** [comment]
Sure. CoreOS operator framework ( https://operatorframework.io/ ) was intended to "implement and automate common Day-1 (installation, configuration, etc) and Day-2 (re-configuration, update, backup, failover, restore, etc.) activities in a piece of software running inside your Kubernetes cluster". This is, of course, not mandatory, but the general idea of perfect "operator" implementation. It's very hard to test and tell which functionality actually present in specific operator unless specific conditions are met. For stand-alone software installation, most of the cases are covered with life cycle management documentation, tools and knowledge base. With operator, control is taken away from the user. I should have read the documentation better, because there are disaster recovery options, but I was not able to spot them.

**Comment by ahmadelrouby** [comment]
@mkuratczyk Could you please tell me the current status of this issue? I'm having an issue with this particular feature: every time the kubernetes nodes reboot, the rabbitmq server doesn't run unless I manually delete all the PVCs and then delete the pods which are then recreated but of course all the data is gone by then. Could please advise on that? does the podManagementPolicy prop work?

**Comment by mkuratczyk** [comment]
Starting with Operator 1.6.0, we use the `Parallel` podManagementPolicy. We haven't seen this issue since. If you are using 1.6.0, your instance is updated (check `podManagementPolicy` on your StatefulSet) and you still see this problem - please open a new issue and provide all details, logs and steps to reproduce.

**Comment by ebuildy** [comment]
doing ``force boot`` is really missing when cluster is broken.

**Comment by mkuratczyk** [comment]
Do you have a problem with a recent Operator version? `podManagementPolicy: Parallel` has been the default for quite some time and solves this problem for all the cases we tested. Please provide additional details of the problem you are facing (a new issue is probably a good idea). Forcing node boot is not something that we should just do automatically.

**Comment by ebuildy** [comment]
Yes, this morning we have removed the STS , hence the 3 pods. Volumes were
not deleted.

When pods came up , I see "boot failed" errors, then pod restarts, after 30
minutes all pods were healthy ! 👍





Le mar. 4 janv. 2022 à 16:18, Michal Kuratczyk ***@***.***> a
écrit :

**Comment by mkuratczyk** [comment]
Please make sure you are using the `Parallel` policy. If yes, please open a new issue with all details and ideally commands to reproduce. The solution you are describing is a way to force a node to boot without waiting for other nodes but with `Parallel` policy, those other nodes should join the cluster around the same.

**Comment by fredgate** [comment]
Can we set the `podManagementPolicy` property to `Parallel` from the start, or does the Statefulset need to be sequential (`OrderedReady`) for the first cluster start ?

**Comment by mkuratczyk** [comment]
Please open new discussions for new questions. `Parallel` is set by default and applies to the initial cluster formation as well (rolling restart and upgrades are still one by one). This has little to do with RabbitMQ - it's just how Kubernetes works.

**Comment by fredgate** [comment]
I wonder if it is safe to use `Parallel` when the cluster builds for the first time.  
My doubt is relative to this comment in the Rabbitmq helm chart of bitnami : https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml#L550
```
## RabbitMQ should be initialized one by one when building cluster for the first time.
## Therefore, the default value of podManagementPolicy is 'OrderedReady'
## ...
podManagementPolicy: OrderedReady
```

**Comment by mkuratczyk** [comment]
There's a long history around this, you can search for `Parallel` in the issues and PRs. The Operator is the recommended way to deploy RabbitMQ to Kubernetes and we believe this is the best solution, at least at this point. If you see issues, report them as bugs.

You can read more here for example: https://github.com/rabbitmq/cluster-operator/issues/662

**Comment by mrocheleau** [comment]
> I wonder if it is safe to use `Parallel` when the cluster builds for the first time. My doubt is relative to this comment in the Rabbitmq helm chart of bitnami : https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml#L550
> 
> ```
> ## RabbitMQ should be initialized one by one when building cluster for the first time.
> ## Therefore, the default value of podManagementPolicy is 'OrderedReady'
> ## ...
> podManagementPolicy: OrderedReady
> ```

It's not possible to start a cluster (that has more than 1 pod/replica) with Parallel set, no.  If you do you wind up with a race condition that gives you unique clusters per pod/replica and they're unaware of each other.

What we've found we've had to do is create the cluster with `OrderedReady` so it comes online correctly, and then delete the rabbitmq statefulset with `--cascade=orphan` to keep the pods operational.  Edit the manifest to have `Parallel` set instead and apply it overtop.  This will tie it into the running pods correctly.

**Comment by VasylSamoilov** [comment]
This is correct, and that is what operator should do as a part of lifecycle management. 
From my point of view, one of the technical solutions may be modified entrypoint helper or init container that is aware of persistent state presence (detect if it is new cluster due to empty PV or data exist on PV) should be in use to help statefulset to create a new cluster with Parallel policy set. Logic should be if there is no data and my pod name is "0" lets create a new cluster, pod name is not "0" - join. If data on persistent volume exist just start unconditionally. 
Creating cluster and deleting statefulset afterwards is a kinda patchy approach to cluster management. But it's the only thing that works for now.

**Comment by VasylSamoilov** [comment]
@mrocheleau  You may try to use this example https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/sidecar to override statefulset spec to add initContainers section with PV mount with one-liner in bash to hold off start if PV is empty and hostname regex is not ending with "-0". Or just check if hostname with index one less than own hostname is reachable - that will replicate OrderedReady behaviour even if start is parallel. Key point here is to check for empty cluster start and just fall thru if data is present, otherwise it will break all DR scenarios.

**Comment by mkuratczyk** [comment]
> It's not possible to start a cluster (that has more than 1 pod/replica) with Parallel set

This is not correct, there are thousands of clusters deployed like that.

There seems to be an issue somewhere which leads to a problem under some conditions. We are still looking for someone who has this problem to actually provide debug logs from all nodes so that hopefully we can fix it. Please stop investing in workarounds and rather, let's fix this problem for everyone.

Lastly, this whole thing will change soon. Mnesia, a database used internally, is what leads to all those issues and solutions. RabbitMQ 3.13 will contain Khepri, our new metadata store, as an opt-in feature and RabbitMQ 4.0 will only support Khepri.

**Comment by mkuratczyk** [comment]
> > > It's not possible to start a cluster (that has more than 1 pod/replica) with Parallel set

> > This is not correct, there are thousands of clusters deployed like that.

> Thousands of clusters deployed doesn't logically leads us to conclusion that bug is not present.

I believe there's a bug, but I can't agree with the statement "it's not possible to start a cluster..." if I personally started hundreds of clusters like that.

> I'm not "investing in workarounds", I'm following your recommendation from 3 years ago. Let me quote: "We introduced the override property exactly to give flexibility and allow users to customize the deployment."
> This is a good thing to know, but while we as a users wait for good things to happen, we still need to maintain whatever exists here and now in working condition.

It's open source software. You can use whatever workaround you want and "maintain whatever exists", but you can also contribute and make your and other people lives easier.

I've deployed many cluster, I've run chaos tests, I haven't seen this issue happen even a single time, so it's not easy to reproduce. Triggering this issue almost certainly requires some condition that is not present in my clusters.

Once again, I'm asking someone who has this issue to actually provide the YAML definition of their cluster and full logs on debug level from all nodes when they didn't cluster correctly.

**Comment by VasylSamoilov** [comment]
I stand corrected. 

There are literally infinite amount of versions, self-baked containers and obscure blog-type articles that will provide examples with outdated versions, custom containers with strange modifications and kubernetes clusters are also vary in quality. 
My initial report was stating all required information and steps to replicate and was valid as of time of writing, for that specific setup only.
If there is any issues similar to this one please create a new ticket describing all necessary version and setup information and provide relevant logging and diagnostics information. 
Closing this issue.
