### ISSUE TITLE
Need an example of adding user and password for management ui

### ISSUE THREAD

**Issue by zeromsi** [rabbitmq/cluster-operator#483]
I need a way to add user and password for management ui with config

**Comment by mkuratczyk** [comment]
Hi. You have a few options to do that:
- you can use standard RabbitMQ tools (https://www.rabbitmq.com/access-control.html)
- you can load definitions on startup (https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-definitions)
- in the future we also want to provide dedicated resources for users (https://github.com/rabbitmq/cluster-operator/issues/12)

**Comment by mkuratczyk** [comment]
Does that answer your question?
