### ISSUE TITLE
How to define the suffix of custom resource name  

### ISSUE THREAD

**Issue by zeromsi** [rabbitmq/cluster-operator#489]
I need to know the attribute of CRD or Operator deployment that controls the  suffix of resource name

**Comment by mkuratczyk** [comment]
We don't provide such a property. Can you explain why you need it?

**Comment by zeromsi** [comment]
When I'm creating a resource, it's creating statefulset with $name-server-0. I want to replace server with my provided string

**Comment by zeromsi** [comment]
> We don't provide such a property. Can you explain why you need it?

If I'm not wrong , I did this previously.

**Comment by mkuratczyk** [comment]
I'm afraid there is no such option.

**Comment by zeromsi** [comment]
> I'm afraid there is no such option.

But I did this previously!

**Comment by mkuratczyk** [comment]
Can you show me how? :)

**Comment by zeromsi** [comment]
> Can you show me how? :)

I just forgot to add the yaml to my ansible, But I doing this in my test server!

**Comment by zeromsi** [comment]
``` abcd-rabbitmq-server-0                            1/1     Running   0          26h ```
This is how it looks

**Comment by mkuratczyk** [comment]
This is most likely an older operator version which called the StatefulSet `INSTANCE-rabbitmq-server`. We changed that a few weeks ago and now we just call the StatefulSet `INSTANCE-server`. If you want "rabbitmq" to be there, just call your instance `abcd-rabbitmq` and that's it.

You can see [here](https://github.com/rabbitmq/cluster-operator/blob/main/internal/resource/statefulset.go#L58) that we add `-server` to the instance name when create a StatefulSet and then the StatefulsSet creates the pods with added `-0` and so on.
