### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by zverev-iv** [rabbitmq/cluster-operator#495]
**Is your feature request related to a problem? Please describe.**

I run on my Windows 10 with docker-desktop, kubernetes and krew installed and got an error:

```powershell
> kubectl krew install rabbitmq
Updated the local copy of plugin index.
Installing plugin: rabbitmq
W1124 21:11:06.246002   28684 install.go:164] failed to install plugin "rabbitmq": plugin "rabbitmq" does not offer installation for this platform
F1124 21:11:06.287004   28684 root.go:79] failed to install some plugins: [rabbitmq]: plugin "rabbitmq" does not offer installation for this platform
exit status 255
```

**Describe the solution you'd like**

I want the plugin to be installed :)

**Describe alternatives you've considered**

alternatively, you please add a footnote to the documentation (https://www.rabbitmq.com/kubernetes/operator/install-operator.html#kubectl-plugin)  that Windows is not supported

**Comment by lukebakken** [comment]
As you have found, Windows is not supported.

Please feel free to open a pull request to change the documentation, which resides here:
https://github.com/rabbitmq/rabbitmq-website/tree/live/site/kubernetes/operator
