### ISSUE TITLE
Add support for TLS rotation without node/cluster restart

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#506]
**Is your feature request related to a problem? Please describe.**
RabbitMQ supports TLS credential rotation without restart - if the cert/key files change on disk, they will be immediately used for new connections (currently open connections stay open). Unfortunately, [we currently use `subPath`](https://github.com/rabbitmq/cluster-operator/blob/e4c3759d2029bce677ded63f5c37bc56319da19c/internal/resource/statefulset.go#L417-L439) to mount TLS credentials and containers with `Secrets` (and `ConfigMaps`) mounted through `subPath` do not receive updates. That means that TLS creds rotation requires a restart to be picked up.

**Describe the solution you'd like**
I'd like to be able to rotate TLS without restart, therefore, if possible, `subPath` should not be used.

**Describe alternatives you've considered**
Perhaps the limitation around `subPath` could be removed from Kubernetes but even if, then it would take a long time before our users would be able to take advantage of that.

**Comment by lukebakken** [comment]
> RabbitMQ supports TLS credential rotation without restart

I guess I've never tried that. I'm assuming the files must retain the same name, correct?

**Comment by mkuratczyk** [comment]
We tested that even with the operator at some point but later on we started using `subPath` and we broke this. It's an implicit feature of RabbitMQ based on the behaviour of `ranch`: https://github.com/ninenines/ranch/issues/293

**Comment by lukebakken** [comment]
Interesting. As noted in [this comment](https://github.com/ninenines/ranch/issues/293#issuecomment-615098163) running `rabbitmqctl eval 'ssl:clear_pem_cache().'` may be a necessary extra step.
