### ISSUE TITLE
kubectl rabbitmq cli plugin should be documented

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#529]
**Is your feature request related to a problem? Please describe.**
There is only documentation about rabbitmq cli plugin briefly in the installing page in rabbitmq.com. The plugin should be better and more extensively documented as we intend for people to use it and have spent time developing the tool for users. https://github.com/rabbitmq/cluster-operator/blob/main/bin/kubectl-rabbitmq

**Describe the solution you'd like**

A dedicated section in our doc about the plugin, and installing the plugin should be mentioned in our quick start guide (https://github.com/rabbitmq/cluster-operator/issues/457) as well.

We should point people to this plugin instead of complicated commands for steps:
[Getting admin creds](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#creds)
[Running perf test](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#verify-instance)

And the plugin also have a command for creating a rmq instance which could be linked here: https://www.rabbitmq.com/kubernetes/operator/using-operator.html#create

**Describe alternatives you've considered**

**Additional context**

**Comment by ChunyiLyu** [comment]
@mkuratczyk Leaving today but I think this doc story should be prioritized.

**Comment by ablease** [comment]
PR is up for review https://github.com/rabbitmq/rabbitmq-website/pull/1143.

**Comment by ablease** [comment]
Merged!
