### ISSUE TITLE
Set log_level through env variable or a flag

### ISSUE THREAD

**Issue by thorion3006** [rabbitmq/cluster-operator#551]
**Is your feature request related to a problem? Please describe.**
Right now the log level for the cluster operator is set at DEBUG, and it's generating a lot of noise. I tried to look for a flag, but the documentation doesn't mention anything about the configuring the cluster operator.

**Describe the solution you'd like**
To be able to set log verbosity through either a flag or env variable. Also detailed documentation on available flags for the operator.

**Comment by ChunyiLyu** [comment]
@thorion3006 It's configurable in our latest release: https://github.com/rabbitmq/cluster-operator/releases/tag/v1.4.0 Let us know if you have anymore questions/feature requests.
