### ISSUE TITLE
Explore and document a workflow to upgrade the Operator

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#56]
## What
We need a workflow to upgrade the Operator. CRD upgrades (e.g. going from RabbitmqCluster v1beta1 to v1) are out of the scope for this issue. We want to explore the risks and impacts of upgrading just the operator. A few questions or scenarios that could help with this explore:

- ~~What happens to existing CR instances when a new version of the Operator is deployed?~~
  - ~~Does it trigger a reconcile for all CR instances?~~
  - ~~Are new defaults applied?~~
- What happens if the new version of the Operator can't be deployed or fails to start?
  - How do we rollback to a working version?
- What do I need to do to upgrade from e.g. 0.7.0 to 0.8.0?
  - Is it different using Helm workflow?

~~Risk: what happens if we introduce a new config map (or any child resource) that requires a modification to STS~~

**Scenario:**

We create a new ConfigMap (e.g. to provide `advanced.config` file for RMQ). This will require a modification to the StatefulSet. In our current model, this should work without issues because we always reconcile the STS inline with our opinions (assuming a rolling restart is not an issue).

This will become an issue when full CRD flexibility #14 is implemented because this will require a change to the STS template. In this scenario, we will create a new ConfigMap that won't be used by the existing STS. It would require manual input to start using this new ConfigMap. How can we address this situation?

## Outcome

- Answers to the above questions
- Update installation docs to include conclusions from the explore to potentially answer user concerns regarding data loss in the control plane, impact on service, etc.

**Comment by j4mcs** [comment]
We have agreed that we need to address versioning to move forward with upgrades (see #190).
Closing this issue in favour of the more specific ideas likely to come out of that work
