### ISSUE TITLE
Improve the cluster restart

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/cluster-operator#574]
I worked on this issue with @ansd 

Problem
---
When the cluster is updated, the `rabbitmq-queues rabalaced all` is called. 
The `rebalace` can take a lot of time to be executed, during this time the reconcile is blocked so the other commands are booked or stored in k8s queue without giving any feedback to the user. 

How to reproduce 
---

- Create a RabbitMQ `Cluster A` with 2 nodes
- Create a mirror policy with 2 nodes
- pump the cluster with few queues / messages
- Scaling up the `Cluster A` to 5 nodes
-  rollout restart sts the `Cluster A`  
- wait for until the `rebalance` si called.

At this point try to deploy a new RabbitMQ `Cluster B`. 
The `Cluster B` won't appear until the the `Cluster A` finishes the `rebalance`. 
If it takes 5 minutes, the user won't see the `Cluster B` for 5 minutes.

This isn't a good user experience. 

Proposal
---
I'd start to give some feedback to the user, maybe add events during `rebalance` and divide it for virtual host

**Comment by mkuratczyk** [comment]
Can we simply execute the command in the background? We don't have any logic to handle errors from this command anyway (apart from logging them) - whatever it does, that's it.

**Comment by ansd** [comment]
@mkuratczyk yes that's a good idea. We were also thinking about that. Trigger the rebalance by running the command in the back ground on a best effort case.
We should avoid synchronous / blocking calls in the reconcile loop.

**Comment by Gsantomaggio** [comment]
@mkuratczyk yes we could, 
We  just have to avoid to run more `rebalance` at the same time
