### ISSUE TITLE
Kubectl plugin can't manage resources in other namespaces

### ISSUE THREAD

**Issue by teozkr** [rabbitmq/cluster-operator#579]
**Is your feature request related to a problem? Please describe.**
The RabbitMQ kubectl plugin only allows managing clusters in the context's default namespace.

**Describe the solution you'd like**
Ideally, `kubectl rabbitmq` subcommands would take the same `--namespace` argument as the rest of `kubectl`.

**Describe alternatives you've considered**
We already create and maintain our cluster resources ourselves (rather than using `kubectl rabbitmq create`). It would've been nice to be able to use the ad-hoc management commands (like `kubectl rabbitmq manage` or `kubectl rabbitmq secrets`), but for now we just manage with the native `kubectl` commands instead.

**Comment by ansd** [comment]
That makes sense.
We should follow the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/):

> Consistency with kubectl
> Krew does not try to impose any rules in terms of the shape of your plugin.
> 
> However, if you use the command-line options with kubectl, you can make your users’ lives easier.
> 
> For example, it is recommended you use the following command line flags used by kubectl:
> 
> -h/--help
> -n/--namespace
> -A/--all-namespaces

**Comment by mkuratczyk** [comment]
I'm almost done with this. It will only support these flags directly after `kubectl rabbitmq` unfortunately but a more flexible solution would require significant changes to the plugin

**Comment by ansd** [comment]
Sounds good. Thanks @mkuratczyk. As long as it's documented in the `help`, that should be good enough.
