### ISSUE TITLE
Upgrading operator and using pause-reconciliation didn't upgrade the cluster pods

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#619]
## Describe the bug
I am running RMQ operator v 1.4.0 with 2 clusters.
Each cluster has 3 replicas.

kubectl rabbitmq list
NAME              AGE   STATUS
rmq-dev-cluster   76d
rmq-qa-cluster    15d

I paused reconciliation on one of the clusters
 kubectl rabbitmq pause-reconciliation rmq-qa-cluster
rabbitmqcluster.rabbitmq.com/rmq-qa-cluster labeled

 kubectl rabbitmq list-pause-reconciliation-instances
NAME             AGE   STATUS   LABELS
rmq-qa-cluster   15d            rabbitmq.com/pauseReconciliation=true

I updated the operator 
 kubectl -n rabbitmq-system apply -f cluster-operator.yml --validate
namespace/rabbitmq-system unchanged
customresourcedefinition.apiextensions.k8s.io/rabbitmqclusters.rabbitmq.com configured
serviceaccount/rabbitmq-cluster-operator unchanged
role.rbac.authorization.k8s.io/rabbitmq-cluster-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/rabbitmq-cluster-operator-role configured
rolebinding.rbac.authorization.k8s.io/rabbitmq-cluster-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/rabbitmq-cluster-operator-rolebinding unchanged
deployment.apps/rabbitmq-cluster-operator configured

The operator pod is upgraded to v1.5.0.

**I expected the the cluster that was not paused (rmq-dev-cluster)  to be updated as well, but nothing happened.
I thought that pausing the reconciliation on one cluster , will not affect the other one.**

Additionally .. 
I resumed reconciliation
 kubectl rabbitmq resume-reconciliation rmq-qa-cluster
rabbitmqcluster.rabbitmq.com/rmq-qa-cluster labeled

kubectl rabbitmq list-pause-reconciliation-instances
No resources found in rabbitmq-system namespace.

And still none of the cluster pods were upgraded ...  I am not sure if that is an expected behavior after resuming reconciliation.. or it should have been upgraded.  

Questions:
1-Is the  pause-reconciliation  should prevent upgrading both clusters ?
2-After resuming ... isn't upgrade supposed to start automatically? 
3-How can  I force the pods to be upgraded now ?

Thanks,

**Comment by mkuratczyk** [comment]
Hi. Thanks for reporting this issue. I can confirm that it works like that in my environment as well so we'll need to fix this.

The intended behavior is:
* on operator upgrade, reconcile all clusters that do not have their reconciliation paused (so in your case, rmq-dev-cluster should indeed be upgraded immediately)
* once reconciliation is resumed, clusters should be reconciled/upgraded

**Comment by bdaoudtdc** [comment]
Thanks Micahl for checking.
Do you believe there is a way to force the clusters to be upgraded now ...

**Comment by mkuratczyk** [comment]
Actually, I believe there is no bug at all. :) The reason nothing is upgraded upon operator upgrade is that no changes to the StatefulSet (or other resources) where introduced between 1.4.0 and 1.5.0. Therefore, the only upgrade that needs to be performed is the change of the `image` property on your clusters that you should perform manually.

Just change `rabbitmq:3.8.9-management` to `rabbitmq:3.8.12-management` in your cluster definitions and you should be fine.
