### ISSUE TITLE
Can't restart single-node RabbitMQ cluster if quorum queue declared

### ISSUE THREAD

**Issue by ansd** [rabbitmq/cluster-operator#622]
## Describe the bug
Can't restart single-node RabbitMQ cluster if quorum queue declared.

## To Reproduce
1. Create a single-node RabbitMQ cluster named `r1`.
2. Declare a quorum queue.
3. `kubectl rollout restart sts r1-server`.

**Expected behavior**
StatefulSet restarts.

**Actual behavior**
The pod is stuck in `Terminating` state.
 
## Additional context
The pod is stuck in `Terminating` state because of https://github.com/rabbitmq/cluster-operator/blob/adc90a66e184a408e0651d3398b6d97284c180eb/internal/resource/statefulset.go#L687
The same can be reproduced without running RabbitMQ on K8s:
Start rabbitmq-server, declare a quorum queue, `rabbitmq-upgrade await_online_quorum_plus_one` will be stuck.

A valid use case is that the user starts with a 1 node RabbitMQ cluster declaring a quorum queue.
In future, the user would like to scale the cluster to 3 nodes without having to re-create the quorum queue.

## Solutions:
* We can skip the `rabbitmq-upgrade await_online_quorum_plus_one` in the operator (same applies to Cloud Foundry in https://github.com/pivotal-cf/cf-rabbitmq-release/blob/bd9b265108455353ec378d946c57f6e03ad58eca/jobs/rabbitmq-server/templates/pre-stop.bash.erb#L28) if desired number of replicas is `1`, or
* This command could be a no-op in RabbitMQ OSS if it's just a single-node cluster.

**Comment by Zerpet** [comment]
This will be addressed in the CLI command. If there is onyl one node, it will be a no-op.

**Comment by Zerpet** [comment]
We can fix this by bumping RabbitMQ in its next release: https://github.com/rabbitmq/rabbitmq-server/pull/2890

**Comment by MirahImage** [comment]
Let's test that the dev image fixes this problem

**Comment by ansd** [comment]
Successfully tested with `image: "pivotalrabbitmq/rabbitmq:f7a36f9f87853077b49a4bc54e23a24c71f9384c"` that this issue is fixed.
Thanks @michaelklishin!
