### ISSUE TITLE
No auto upgrade when pause reconciliation is used  (details in issue #619)

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#624]
Actually, I believe there is no bug at all. :) The reason nothing is upgraded upon operator upgrade is that no changes to the StatefulSet (or other resources) where introduced between 1.4.0 and 1.5.0. Therefore, the only upgrade that needs to be performed is the change of the `image` property on your clusters that you should perform manually.

Just change `rabbitmq:3.8.9-management` to `rabbitmq:3.8.12-management` in your cluster definitions and you should be fine.

_Originally posted by @mkuratczyk in https://github.com/rabbitmq/cluster-operator/issues/619#issuecomment-785263945_

**Comment by mkuratczyk** [comment]
That comment doesn't describe an issue but the current intended design. Can you provide what you'd expect exactly?
We've heard from lots of users that they do not expect RabbitMQ upgrades to be automatically triggered as soon as the Operator is upgraded (or reconciliation resumed).

**Comment by bdaoudtdc** [comment]
Hello .. sorry I was still adding my comment 
As you suggested , I can  manually add the value of the new image to my definition file  to force the usage of the new image.

spec:
  image: rabbitmq:3.8.12-management

My definition file , doesn't explicitly have an option for the image , but as you suggested it can be added.

So by design ... Is an upgrade to an operator (or reconciliation resumed) is not supposed to cause an upgrade to the existing cluster unless there are changes in the StatefulSet .  Please confirm


Now, I added a new cluster and I see that RabbitMQ 3.8.12  &  Erlang 23.2.6.

How can Erlang be updated on the existing clusters.  Is also upgrading Erlang is intended to be explicitly added to the definition value of the cluster.

Thank you for your help.

**Comment by mkuratczyk** [comment]
`image` is injected by the operator if you don't specify it. Just have a look at `kubectl get -o yaml rabbitmq foo` and you'll see that the image is now explicitly there and therefore - your cluster pinned to that version until you change it. Updates to the statefulset happen on the next reconciliation. This is a somewhat unfortunate side effect of Statefulset details not being present in the `RabbitmqCluster`. This design may change in the future but right now that's what happens. Hopefully, as the operator matures, `StatefulSet` changes won't happen too often so the Operator update won't trigger any action on your clusters.

Erlang is part of the image and therefore will be updated when you bump the image (usually both RabbitMQ and Erlang will be updated in a new image version).

**Comment by bdaoudtdc** [comment]
Thanks for the clarification.
