### ISSUE TITLE
Improve support for importing definitions

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#631]
Currently we don't provide explicit support for importing definitions. It's possible using `override` as [documented in the example](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-definitions). There are however a few problems with this approach.

1. ConfigMap has a limit of 1MB while definitions that far exceed that value are not uncommon
2. Becasue all pods are the same, they all have the same additional volume and configuration option. Therefore the definitions are imported as many times as there are nodes. Importing existing definitions is generally quite a bit faster but this can still take minutes with a large definitions file.
3. It's a fairly standard process and yet requires `override` which should be reserved for unusual configurations

We should discuss how far we want to go with this but some ideas to consider:
1. top-level property for definition volume/configmap
3. option/default to skip re-importing the same definition file on multiple nodes
4. perhaps a core RabbitMQ option to ignore definition files with a known checksum? record it on the first import, ignore next time (this would prevent the same file being reimported)
5. support for compressed/external (HTTP?) definition files?

Reimporting is only an issue with large definition files, if at all, so supporting large definitions should take priority over the multi-node optimization.

**Comment by Zerpet** [comment]
Related https://github.com/rabbitmq/cluster-operator/issues/321

**Comment by Zerpet** [comment]
> 3. It doesn't allow different definitions to be loaded on different nodes

Metada (i.e. vhosts, users, queues, etc.) is shared among all nodes in the cluster, so importing different definitions per node would yield the same result as importing all definitions to one node of the cluster. What's the use case for this?

> 4. It's a fairly standard process  [...]

We have been asked a few times about this. I'm unsure if it's "standard", but it's worth easing the process.

**Comment by mkuratczyk** [comment]
Definitions are shared between nodes but there can be other factors. For example, with `client-local` placement policy and non-mirrored queues, importing all definitions to a single node means one node doing all the work. Importing different sets to different nodes can be a way to spread the queues (rebalancing doesn't work for non-mirrored queues so that's not an alternative). It's probably a corner case but something to keep in mind.

**Comment by mkuratczyk** [comment]
We have discussed this with @yaronp68 and @michaelklishin and the following sounds like a good idea:

1. Top-level `RabbitmqCluster` spec field to specify a ConfigMap/Secret with the definitions. These definitions would not be included in the config file though. Instead, after all nodes are up, we can call a CLI to import the definitions. The benefits:
a. import once per cluster
b. import when all nodes are up so that queues get distributed among nodes
c. `skipPostDeploySteps: true` could be used to skip the import on restart - this could be useful if the user needs to restart pods but knows the definitions didn't change and wants to speed up the process

Given the 1MB limitation of ConfigMaps and Secrets, we would also need an option to specify a volume and a path on that volume. The user would then be able to:
* create a volume
* put the definitions on the volume
* deploy a `RabbitmqCluster` with that volume mounted
* definitions would be again imported through a CLI

A third option could be to have an init container download a file. This would probably be easier for the user (since a large definition file is probably stored in Git somewhere anyway) but may require us to support quite a few options like HTTP and Git, with and without TLS, with and without different auth. If we do that, the spec should contain the URL (and additional necessary details) as well as a SHA to check that what was downloaded was indeed the expected file (eg. to avoid accidentally importing newer definitions on restart)

**Comment by michaelklishin** [comment]
@mkuratczyk another option would be to add a new option, e.g. `load_definitions_from_url`, that would allow RabbitMQ nodes to download the definitions file from a remote location. That won't have the context the Operator has (e.g. so that it is only done once per cluster formation/boot) but it was discussed as well, so I'm mentioning it.

**Comment by MirahImage** [comment]
Closing, as this work has been done using the load_definitions_from_url option
