### ISSUE TITLE
Add support for Global Parameters

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#654]
**Is your feature request related to a problem? **
[Global Parameters](https://www.rabbitmq.com/parameters.html#parameter-management) can be used to configure certain features, such as continious schema replication. We want to have a method to configure this via the Kubernetes API.

**Describe the solution you'd like**
The Cluster Operator will have a new property to represent Global Parameters. It can have any number of Global Parameters. It should support creation, update and deletion of Global Parameters.

**Describe alternatives you've considered**
None.

**Additional context**
We might have to think of the scenario of having multi-master Kubernetes cluster and consider scenarios described in #648.

**Comment by ChunyiLyu** [comment]
Decided to implement as a dedicated crd in topology operator, related issue and PR:
https://github.com/rabbitmq/messaging-topology-operator/issues/112
https://github.com/rabbitmq/messaging-topology-operator/pull/113
