### ISSUE TITLE
Documentation for migrating cluster operator to air-gapped environments is missing the instance image

### ISSUE THREAD

**Issue by odedia** [rabbitmq/cluster-operator#659]
The docs as listed here:
https://www.rabbitmq.com/kubernetes/operator/install-operator.html#relocate-image

Describe how to relocate images to an air gapped environment:

```
docker pull rabbitmqoperator/cluster-operator:{some-version}
docker tag rabbitmqoperator/cluster-operator:{some-version} {someregistry}/cluster-operator:{some-version}
docker push {someregistry}/cluster-operator:{some-version}
```

In real-world scenarios, the user will also need to relocate the RabbitMQ instance as well. I recommend adding reference to relocate the `rabbitmq:3.8.12-management` image as well, and also how to add the updated referenced `image:` in the RabbitmqCluster yaml file.

Thanks.

**Comment by coro** [comment]
This looks like something that kbld in the Carvel tooling is well suited to handling - https://carvel.dev/kbld/docs/latest/packaging/

Perhaps we could write something explaining how to relocate everything at once with kbld?
