### ISSUE TITLE
How to set policies?

### ISSUE THREAD

**Issue by akashsethiya** [rabbitmq/cluster-operator#666]
how to set the below policies using the kubernetes operator or frontend or rabbitmqctl is the only option
- `ha-mode`: `all`
- `ha-sync-mode`: `automatic`

**Comment by mkuratczyk** [comment]
Hi,

1. Please avoid using classic mirrored queues. They will be deprecated and removed in the future. If you care about data safety, use quorum queues instead (quorum queues don't require policies like that at all).
2. There is a Topology Operator which allows defining policies: https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/policies
3. If you have access to `rabbitmqctl`, you can follow https://www.rabbitmq.com/parameters.html
4. You can use the Management UI
5. You can use import definitions feature to import policies (and other things on startup): https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-definitions
