### ISSUE TITLE
RMQ Operator removes unknown labels from owned resources

### ISSUE THREAD

**Issue by Samze** [rabbitmq/cluster-operator#702]
## Describe the bug
Custom labels added to RMQ owned resources (e.g. secret/services) are removed by the RMQ Cluster Operator.

## To Reproduce
Steps to reproduce the behaviour:
1. Install RMQ Operator 
1. Install a new instance of a RabbitMqCluster
1. Add a custom label to the `default-user` secret
1. Fetch the secret and observe that the custom label has been removed.

**Expected behavior**
I did not expect the Operator to remove the labels. This may make it harder for users or 3rd party integrations that want to use labels.

From [API convention docs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata):
```
Labels are intended for organizational purposes by end users (select the pods that match this label query). Annotations enable third-party automation and tooling to decorate objects with additional metadata for their own use.
```

## Version and environment information
- RabbitMQ Cluster Operator: 1.70

**Comment by ChunyiLyu** [comment]
Hi @Samze, child resources inherit labels from their rabbitmqclusters and additional labels would be removed. We've made this design decision based on the assumption that users shouldn't interact with any of the child resources directly. I will convert this bug to a feature request and bring it up in our next sync up. In the mean time, could you provide some use case examples where this feature is required by a 3rd party integration?
