### ISSUE TITLE
Admin credential warning in the logs 

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#734]
## Describe the bug
We have a 3 node cluster.
The cluster is configured with LDAP.
We see this message repeated over and over ...
[warning] <0.1548.0> Searching for DN for 6vvcLXv-fMICLP-or9fFCewp1R0haTfy, got back []
where  6vvcLXv-fMICLP-or9fFCewp1R0haTfy is the username of the default admin.

We have users logging using ldap and we have local users used by applications.
No one is using the default admin.

Any reason why this happening or how to fix it ..

## Version and environment information
- RabbitMQ: [3.8.12]
- RabbitMQ Cluster Operator: [1.7.0 ]
- Kubernetes: [e.g. 1.17.13]

**Comment by bdaoudtdc** [comment]
For my ldap config , I am using 
auth_backends.1 = ldap
auth_backends.2 = internal

What worries is me ..is what is using the default admin user .. is that normal.

**Comment by coro** [comment]
Hi @bdaoudtdc , just to double check, are you also using the [messaging topology operator](https://github.com/rabbitmq/messaging-topology-operator)? I know that operator uses the cluster's default user for creating topology objects.

**Comment by coro** [comment]
If you are using the kubectl plugin `kubectl rabbitmq`, I believe that retrieves the default user credentials for some actions as well.

**Comment by bdaoudtdc** [comment]
Hello, No I am not using the messaging topology operator and I am not also using the kubectl rabbitmq plgugin, but I have it intsalled.

**Comment by coro** [comment]
@bdaoudtdc Is there any regularity to how often these messages appear? I.e. exactly every X seconds, or randomly throughout the day?

**Comment by bdaoudtdc** [comment]
There is some sort of a pattern .. at the top of each minute ...
0-3 secs  (3-4 times/sec)
4-16 sec  ( nothing)
17-21 sec  (3-4 times/sec)
22-59 sec  (nothing)

**Comment by coro** [comment]
At the times where those connections occur, do you see anything of interest from running `rabbitmqctl list_connections`?

**Comment by bdaoudtdc** [comment]
Nothing special about the connections at these times ..
I am not using this admin account anywhere else .. is it used by any inter-node communication ...or something done by the operator.

**Comment by ChunyiLyu** [comment]
Hi @bdaoudtdc, do you still have the same issue with you RMQ cluster?

**Comment by bdaoudtdc** [comment]
Yes I still have the same issue.
Although I believe that it may be happening because  of my authentication order 
auth_backends.1 = ldap
auth_backends.2 = internal

If I change the authentication order ..  I will not see this message 
 [warning] <0.1548.0> Searching for DN for 6vvcLXv-fMICLP-or9fFCewp1R0haTfy, got back []
where 6vvcLXv-fMICLP-or9fFCewp1R0haTfy is the username of the default admin.

the ldap config just indicated to me that the default admin account is logging all the time .. but I don't know why .. is that by design.
Thanks,

**Comment by coro** [comment]
Hi @bdaoudtdc, sorry for the delay. Many things can trigger authN / authZ flows in RabbitMQ using the default user, such as monitoring, open management UI tabs, etc. As you noted, if ldap is listed as the first auth backend, it will be tried first, before succeeding on the internal backend. The log is expected in this case. Hope that helps!

**Comment by bdaoudtdc** [comment]
Thank you for the clarification.
