### ISSUE TITLE
Is RabbitMQ 3.9 compatible with the community plugins example?

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/cluster-operator#748]
Since plugins are now directories and not ez files - do you remember which PR was this @dumbbell ? - does the [community plugin example](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/community-plugins) still work?

Suggestion: the easiest thing could be to test it in this context: https://github.com/rabbitmq/infrastructure/blob/master/k8s/gke/long-running-environments/lre-3-9/rabbitmq.yml

Extra context: came up while pairing with @Zerpet on Tanzu RabbitMQ v1.x

**Comment by mkuratczyk** [comment]
Seems to work fine:
```
$ cd cluster-operator/docs/examples/community-plugins
$ kubectl apply -f rabbitmq.yaml
$ kubectl exec -ti community-plugins-server-0 -c rabbitmq -- rabbitmq-plugins list | grep timestamp
[E*] rabbitmq_message_timestamp        3.8.0
```

**Comment by gerhard** [comment]
Is that rabbitmq_message_timestamp v3.8.0 plugin in the context of RabbitMQ 3.9.0? If yes, then happy for this to be closed.

**Comment by mkuratczyk** [comment]
I messed up the test. Indeed, doesn't work on 3.9 but for other reasons than expected:
```
[warn] <0.221.0> Failed to enable some plugins:
[warn] <0.221.0>     rabbitmq_message_timestamp:
[warn] <0.221.0>         Plugin doesn't support current server version. Actual broker version: "3218e2d54d4334af37045b71be61a8a877500118", supported by the plugin: ["3.7.0-3.7.x", "3.8.0-3.8.x"]
```

This is with `image: pivotalrabbitmq/rabbitmq:v3.9.x-otp-max-1`. So it's harder to test but also seems like the plugin is picked up, just not loaded due to declared version dependency.

**Comment by gerhard** [comment]
In which case, maybe we should release a 3.9 version of the `rabbitmq_message_timestamp` plugin and make sure that it works correctly in 3.9.0. After 3.9.0 GA ships, it may be worth adding a section to that example that takes into account the new plugin format (which is directories, not `*.ez` files).

Does this sound reasonable to you @michaelklishin?

**Comment by dumbbell** [comment]
The plugin format didn't really change. It's just easier for packagers and us that the tier-1 plugins are shipped as directories. Otherwise, tier-1 plugins are zip files inside the package (often a tar archive compressed with gzip, bzip2 or xz) and packages are larger than when plugins are directories. Also, RabbitMQ will uncompress them on boot every time which is useless.

But 3rd-party plugins are easier to distribute as a single `.ez` file.

**Comment by gerhard** [comment]
So any plugins which are distributed and included as .ez files will work as before, the only change is the built-in plugins which are now directories. If that's the case, please close this issue @dumbbell 👍🏻

**Comment by dumbbell** [comment]
I'm just saying the format is irrelevant to plugins compatibility. They are still Erlang applications, whether they are a directory or a zip archive of that same directory.

That doesn't mean 3rd-party plugins do work with RabbitMQ 3.9.0.

**Comment by gerhard** [comment]
I understand. I'm closing this as the initial question was answered.

Now we just need to find a community plugin for 3.9 and check that something other than the `.ez` is not preventing it from working properly in the upcoming RabbitMQ 3.9.0.

FTR https://github.com/rabbitmq/rabbitmq-server/discussions/3184
