### ISSUE TITLE
Rebalance queues after initial cluster startup

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#759]
In https://github.com/rabbitmq/cluster-operator/pull/385 we implemented queue rebalancing after a rolling restart. However, if definitions are imported through configuration, even a newly deployed cluster may be unbalanced. It is therefore worth rebalancing it after the initial deployment.

While we could add a condition to only do that if definitions are imported, I don't think it's worth it - if they are not, the command will simply execute very quickly as there will be nothing to do.

**Comment by mkuratczyk** [comment]
Perhaps unnecessary if we implement https://github.com/rabbitmq/cluster-operator/issues/631

**Comment by Zerpet** [comment]
@mkuratczyk I believe we can close this issue given that this was fixed in the core. WDYT?

https://github.com/rabbitmq/cluster-operator/issues/631#issuecomment-1096554711

**Comment by mkuratczyk** [comment]
Indeed. While validating it works as expected, I updated the import-by-URL example. The leader are well balanced after deploying this example.
