### ISSUE TITLE
CRD Multiple Versions Notes

### ISSUE THREAD

**Issue by ferozjilla** [rabbitmq/cluster-operator#77]
## How conversion webhooks work

CRDs are able to describe multiple API versions thanks to the use of the [Open API V3 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). In order for Kubernetes to manage the work of maintaining serving multiple versions, a few conventions have been made:
- A client must be able to request any version that is being served and expect the data to reflect the API of that version
- By default, when you fetch a Custom Resource instance, you will get the latest available serving version
- The author of the Operator must specify a storage version that will be used as the data model to store all metadata in the Kubernetes database.

This means that:
- A controller can specify any version that it would like to reconcile. You can have multiple controllers reconciling different versions if necessary. This does introduce more complexity so the use case for multiple controllers should be justified (this demo does not implement multiple controllers).
- A storage version needs to be able hold all metadata for all API versions.

### The storage version
Kubernetes will use a designated version to store metadata for all API versions. When multiple versions are being served by a CRD, a conversion to the storage must happen before the Custom Resource instance is persisted.

```
----------------------------        --------------        --------------       --------------
|                                           |  V2    |                     |  V2 |                     | V1  |                      |
| kubectl apply -f v2.yaml |----->| Reconcile    |--->| Conversion |--->| k8s              |
|                                           |          |                      |       | Webhook     |       | Database    |
----------------------------        --------------        --------------       --------------
```

Metadata must not be lost across conversions

The implementation of a storage version means that it must contain all forms of metadata for all versions. This can either be persisted in annotations or in the API of the storage version itself.
```
                                                   --------------------------------
                                                   | apiVersion: V1                           |
                                                   | metadata:                                  |
                                                > |   annotations:                            |  
                                               /   |     ‘{spec.version2Prop: true}’  |
                                             /     | spec:                                          |
                                           /        --------------------------------
|-----------------------|/
| apiVersion: V1              |
| spec:                             |
|   version2Prop: true     |
|-----------------------|\
                                            \        |-----------------------|
                                              \      | apiVersion: V1              |
                                                \    | spec:                             |
                                                  > |   version2Prop: true     |
                                                     |-----------------------|
```

Keeping state in annotations is more flexible and easier to implement the saving of metadata. However, it complicates matters for the conversion webhook. In order to unpack the state in annotations and marshal that data into a struct, the webhook must first inspect the data to know what version to marshal data into (see comments [here]()).

Having the storage version contain `version2Prop` removes the complexity in the conversion webhook, however then you have a leaky API that contains properties that this version cannot utilise. This could potentially lead to reconciliation errors down the line.

### Two demos

We will suggest two possible solutions to implementing conversion webhooks into our workflow. 

Please follow the steps provided in the readme of the [multiversion crd demo]( https://github.com/pivotal/multiversioncrd-demo)

This example requires an operator and two API versions: v1 and v2. The operator follows the example set out in [kubebuilder](https://book.kubebuilder.io/multiversion-tutorial/tutorial.html) and implements a simple cronjob job deployment. v1 has a schedule property that is simply of type `string`, and v2 has a schedule property that is a struct of type `CronSchedule`.
The demo guides you through creating instance `sample-one` that is v1, and `sample-two` that is v2.

When you run `make sample-one-schedule-as-v1`, as detailed in the demo steps, you will see the schedule of `sample-one` as it should be, in its string form. However, when you run `make sample-one-schedule-as-v2`, you will see the schedule in its `CronJob` struct form.

This is a demonstration of the philosophy of multiple versions. There is no concrete idea of a Custom Resource that simply stays at one version, but can be viewed and modified as any serving version. You can modify `sample-one` either as a v1 object, or a v2. You can follow the demo steps to see this for yourself.

### Further Explores
Investigate how multiple controllers react to the watch events of different api versions.
Does every controller have their reconciliation loop triggered on the change event of every api version, or simply the api version it wishes to reconcile.

**Comment by ChunyiLyu** [comment]
Closing stale issue.
