### ISSUE TITLE
Allow creating clusters without persistence

### ISSUE THREAD

**Issue by the-smooth-operator** [rabbitmq/cluster-operator#776]
**Is your feature request related to a problem? Please describe.**
I would like to use the operator to create disposable RabbitMQ clusters without persistence enabled.

**Describe the solution you'd like**
`RabbitmqClusterPersistenceSpec` be controlled by a boolean `persistence: bool` which will allow not creating any persistent volume.

**Comment by ansd** [comment]
Do you mean a RabbitMQ Cluster with [RAM nodes](https://www.rabbitmq.com/clustering.html#ram-nodes)?
Why do you want this?

**Comment by TheRealDwright** [comment]
> RAM nodes

A use case I have for this is when creating an ephemeral environment. For example our static environments which use the operator we do want persistent volumes to be used, however for feature builds we'd like to continue using disk storage to maintain consistent performance characteristics with our static environments but not create a PVC and unnecessarily utilise node volume attachment limits.

It's far easier to simply toggle a persistent storage flag on/off than it is to conditionally deploy RAM nodes.

**Comment by the-smooth-operator** [comment]
> Why do you want this?

I want this in order to use less resources and have less overhead when deploying disposable RMQ clusters for testing.

During application's CI, I use the operator to create a RMQ cluster, applications connect to it, create queues, test connections and publishing/consuming messages. In a matter of minutes, the CI process completes and the RMQ cluster is deleted.

**Comment by mkuratczyk** [comment]
Support for this feature has now been merged and will be shipped in the next release. If you set `.spec.persistence.storage: 0`, the PVC won't be created (an `emptyDir` will be used instead).
