### ISSUE TITLE
SERVER ALERT: Fatal - Unknown CA

### ISSUE THREAD

**Issue by kotyara85** [rabbitmq/cluster-operator#796]
Hello,
I'm trying to enable federation using TLS and getting this error
```
{{socket_error,{tls_alert,{unknown_ca,"TLS client: In state connection received SERVER ALERT: Fatal - Unknown CA\n"}}},
 {expecting,'connection.start'}}
```

Bot certs generated using self-signed certs with manager cert-manager.io/v1alpha2

Here's the connection string I'm using -

```
amqps://user:passsword@rabbitmq.localhost:30476?cacertfile=/opt/bitnami/rabbitmq/certs/ca_certificate.pem&certfile=/opt/bitnami/rabbitmq/certs/server_certificate.pem&keyfile=/opt/bitnami/rabbitmq/certs/server_key.pem
```

This does work fine without TLS

TLS verification passes from the console -
```
    Verify return code: 0 (ok)
```

I guess it's somehow related to self signed certs, right?

Thanks

**Comment by kotyara85** [comment]
Resolved after specified these in helm chart
```
    --set auth.tls.sslOptionsVerify=verify_none \
    --set auth.tls.failIfNoPeerCert=false \
```

**Comment by mkuratczyk** [comment]
Also, please note that you seems to be using the Helm Chart and not the Operator. Therefore this repo is the wrong place for raising issues related to your deployment. But I'm glad you found a solution. :)

**Comment by michaelklishin** [comment]
Instead of disabling peer verification, I'd instead [learn what the Unknown CA TLS alert means](https://rabbitmq.com/ssl.html#peer-verification-how-it-works) and ensure the necessary CA certificates are trusted on the nodes acting as Federation downstream (so, a TLS client).

**Comment by kotyara85** [comment]
@michaelklishin i know what mtls is, lol. 
unfortunatelly it didn’t work with rabbitmq and self signed certificates.
