### ISSUE TITLE
open: command not found

### ISSUE THREAD

**Issue by Loki-Afro** [rabbitmq/cluster-operator#801]
Hi,

open results mostly in command not found in a linux environment, usually xdg-open is what you meant. open is mac specific afaik

https://github.com/rabbitmq/cluster-operator/blob/aecf155cf2d43bb28d555e49b784f9352b7dc299/bin/kubectl-rabbitmq#L169

```
zarathustra@wotan ~ % kubectl rabbitmq manage hello-world                                                                                                                                 
Forwarding from [::1]:15672 -> 15672
/home/zarathustra/.krew/bin/kubectl-rabbitmq: line 169: open: command not foun
```

running on up to date fedora :)

**Comment by Zerpet** [comment]
Thank you for reporting this! I created a PR to adapt the script based on the platform. The fix will be in our next release.
