### ISSUE TITLE
Node restarts take a very long time

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#805]
## Describe the bug
We have a cluster of 3 nodes.
All our queues are quorum queues.
If we change any of the config parameters in the YAML file , node restarts may take between 10-40 mins
It takes a very long time to terminate a pod.
The time taken for terminating a pod is random and the long time is not happening on any particular pod.
It may happen on any of the 3 nodes.

**Expected behavior**
That restart takes less than 3-4 mins of all nodes

## Version and environment information
- RabbitMQ: [ 3.8.12]
- RabbitMQ Cluster Operator: [ 1.7.0 ]
- Kubernetes: [e.g. 1.17.13]
This issue has been there since earlier operator versions like 1.2.0 and above.

**Comment by Zerpet** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
