### ISSUE TITLE
Messages lost when nodes restarts

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#806]
## Describe the bug
We have a cluster with 3 nodes.
In the event of nodes restarts because of changing a config value in the YAML file , we see messages loss.
We use quorum queues.
We are using publish confirm & consumer ack.
We believe the messages are lost between RMQ & the consumer
If the consumer is down , we don't see loss of messages.

**Expected behavior**
We don't except any loss of messages 
 
## Version and environment information
- RabbitMQ: [3.8.12]
- RabbitMQ Cluster Operator: [ 1.1.7 ]
- Kubernetes: [e.g. 1.17.13]

**Comment by Zerpet** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
