### ISSUE TITLE
Update default user's password in RabbitMQ when it has changed in Vault

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/cluster-operator#823]
# Context
This feature is part of the vault integration opportunity. It is about rotating the default user's password. Not the username !

# Scope
Vault Agent (a.k.a. sidecar) keeps a RabbitMQ config file with the default user's credentials in sync with Vault. In other words, when the credentials change in Vault, the agent updates the local file in the cluster's pod.
We need a sidecar that monitor the local config file in the pod and updates RabbitMQ. Either by means of the management rest api or via rabbitmqctl (doing exec onto the rabbitmq container)

**Comment by twhite0** [comment]
@MarcialRosales:  
We've used the [Vault Agent](https://www.vaultproject.io/docs/agent) with some success at fetching and initiating a command when credentials have changed.  In particular the [command](https://www.vaultproject.io/docs/agent/template#command) portion of the template allows for the agent to initiate a _simple_ command.  
We have products using this along with a _refresh_ endpoint which updates the credentials (command = curl ....).  We have other products which prefer to simply initiate a new Deployment on a credential change (command = kubectl ...).  They are incrementing an environment variable on the sidcar container such that all running pods will update/noop to the same value.  This does require patch access to the ServiceAccount in use which may be an issue in some shops.

**Comment by MarcialRosales** [comment]
@twhite0 Thanks! that is indeed very convenient. In our initial exploration we opted to monitor the file. But invoking a command is far neater.

**Comment by MarcialRosales** [comment]
@twhite0 :
We have tried the [command](https://www.vaultproject.io/docs/agent/template#command) option however we are limited by the commands available in the image that vault agent runs (`hashicorp/vault:1.8.1`). This docker image has a rather old/limited `wget` version (`BusyBox v1.32.1 `) which only supports  http `GET` method. However, in order to rotate the password in RabbitMQ, we would need `PUT` or `POST`. 

We are no longer very keen on our initial approach of having sidecar watcher container. This leaves us with just one alternative  -at least for now- which is the following:  Use  "**stateful override**" feature to set `vault.hashicorp.com/agent-image` annotation with a **customer-provided-image** which has all the necessary runtime (e.g. wget + some scripts)  to rotate the password in RabbitMQ.  what do you think? Based on your comment [above](https://github.com/rabbitmq/cluster-operator/issues/823#issuecomment-910663881) you must be using a custom image with either `curl` or `kubectl`.

**Comment by twhite0** [comment]
>  Based on your comment above you must be using a custom image with either curl or kubectl

We use ubi-minimal as our base image which has `curl` on it.  We then add on the vault CLI.

>  Use "stateful override" feature to set vault.hashicorp.com/agent-image annotation with a customer-provided-image which has all the necessary runtime (e.g. wget + some scripts) to rotate the password in RabbitMQ. what do you think?

We haven't graduated to using the mutation pattern for injecting Vault.  At this time we're explicitly defining sidecars/initCs.  I'm assuming that regardless of how we define it (vault injection or sidecar) the credentials will be persisted onto a shared mount with RabbitMQ.  I'm unfamiliar with what needs to occur at that point?  Will RabbitMQ automatically reread the creds?  Does it need signal or cli command?

**Comment by MarcialRosales** [comment]
For rotating default-user's password , we call `curl -XPOST .. /api/definitions`. This is assuming we are only rotating the password. If we had to rotate the username too, we would call two more commands. This is so that we preserve the old username's permissions on the new username. Furthermore, we also need to delete the old username. 

For TLS, we do not need to call any command. The vault agent overrides the pki files (cert, key) when the certificate expires. And RabbitMq automatically picks up those new private and certificates.

**Comment by twhite0** [comment]
@MarcialRosales:  Apologies for not getting back sooner.  We've been toiling internally on the username/password rotation aspects of Rabbit+Vault.  Internally we need to be able to rotate the creds periodically, however we're not confident in how to do this with existing definitions in Rabbit.

**Comment by ansd** [comment]
Closing since https://github.com/rabbitmq/cluster-operator/pull/846 is merged.
