### ISSUE TITLE
To create a cluster with TLS enabled, the certificate and private key should come from Vault's secret

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/cluster-operator#824]
Context
This feature is part of the Vault integration opportunity. The goal is not to use K8s secrets to store any RabbitMQ secret such as a default user's credential or TLS cert/keys. Instead, these secrets should be in Vault and retrieved with the appropriate Vault authentication mechanism.

Scope
When the operator creates a cluster, it should retrieve the TLS certificate and private key from Vault rather than from a secret. We use Vault Agent (a.k.a. sidecar) to retrieve both files from Vault and store them in the pod's in the exact same locations where RabbitMQ expects them. Rotation is given for granted because Erlang will automatically picks the new cert/key when their corresponding files change.

Given that we are only enabling TLS, and not mTLS, we do not seem to need to retrieve the ca certificate used to validate client's certificates.

**Comment by twhite0** [comment]
@MarcialRosales:

We would be interested in this functionality.  Do you have thoughts on if this would be configured to use a [PKI backend](https://www.vaultproject.io/docs/secrets/pki) or generated _out of band_ and stored in a KV2 for retrieval?

Thanks in advance.

**Comment by MarcialRosales** [comment]
Hi @twhite0 , indeed we are supporting PKI backend. You will see in the examples we provide that you need to specify the path to the `pki/issue/<role>` of your choice. 
There is no need to have the PKI artifacts in a kv store path.

**Comment by ansd** [comment]
Closing since https://github.com/rabbitmq/cluster-operator/pull/846 is merged.
