### ISSUE TITLE
Network policy resource

### ISSUE THREAD

**Issue by ebuildy** [rabbitmq/cluster-operator#835]
**Is your feature request related to a problem? Please describe.**

In a production environnement, all network traffic is blocked between pods, we must declare network-policy to allow traffic between operator and rabbitmq server pods.

**Describe the solution you'd like**

The operator should create this network policy.

**Describe alternatives you've considered**

Create mannually the network policy, hard to figure out traffic rules between operator and servers pods (which ports ?)

**Comment by coro** [comment]
We talked about this in our team sync up today; I don't think this is something we can create automatically, as we don't know whether your client apps connecting to RabbitMQ are in Pods on the same cluster, or if they're running off Kubernetes altogether, and once the RabbitMQ Pods are targeted by a NetworkPolicy, they become isolated to traffic unless permitted by a NetworkPolicy. It also doesn't seem appropriate for this operator to be responsible for managing the networking topology of a user's apps.

What we can do is document examples of NetworkPolicies that you may want to apply to help with the manual process of defining them. Would that help you?
