### ISSUE TITLE
Unable to find Messages and Message Rates columns in Management UI

### ISSUE THREAD

**Issue by Komaldua** [rabbitmq/cluster-operator#844]
I have rabbitmq installed on my local machine and as a statefulset on my kubernetes cluster. The management UI on my local machine shows the Messages section on queues page with count of read messages. Even though I have enabled the same columns on my management ui on the cluster, I still can't see the same details.

Local Management UI Screenshot
![image](https://user-images.githubusercontent.com/81220602/133736191-285c71b7-12bf-4632-8d53-293cb0285376.png)

Cluster Screenshot
![image](https://user-images.githubusercontent.com/81220602/133736403-a9831d0f-dea3-4241-81ed-c0c4722fbed1.png)

**Comment by mkuratczyk** [comment]
I cannot reproduce. I deployed a cluster with all the defaults and the same version:
```
kubectl rabbitmq create foo --image rabbitmq:3.9.5-management
```
And I see queue stats when I log in to Management UI (no need to select columns in my case). 

I can see in the upper right corner of your screenshot that the Management UI could not connect to RabbitMQ. Perhaps the columns disappear when the UI can't fetch the values?

**Comment by Komaldua** [comment]
@mkuratczyk  Please see the screenshot below: my session had expired 
![image](https://user-images.githubusercontent.com/81220602/133764878-f36051be-a8c3-4ef2-9cf8-48d151d3751f.png)

Thanks for quick response

**Comment by mkuratczyk** [comment]
Can you try with a new cluster? 
```
kubectl rabbitmq create foo --image rabbitmq:3.9.5-management
kubectl rabbitmq perf-test foo --rate 1
kubectl rabbitmq secrets foo
kubectl rabbitmq manage foo
# check the UI
```
If this works, how does this differ from what you did with the existing cluster?
