### ISSUE TITLE
Distribute operator image on multiple registries

### ISSUE THREAD

**Issue by torblerone** [rabbitmq/cluster-operator#869]
**Is your feature request related to a problem? Please describe.**
The new pricing model of Docker Inc. is making it hard to still use DockerHub as a public image registry for businesses without paying for it. There's plenty other public registry providers that can be used.

**Describe the solution you'd like**
Maybe `quay.io`?

**Comment by Zerpet** [comment]
We are planning to publish our images to GitHub Container Registry, in addition to DockerHub. It's not clear whether we'll stop publishing to DockerHub.

**Comment by torbendury** [comment]
Hello @Zerpet, are there any news on this, any ETA? :slightly_smiling_face:

**Comment by Zerpet** [comment]
Hey folks, I brought this up to the team a few days ago, and we decided that it makes sense to publish to `quay.io`. I'm exploring that registry and noting down what needs to be done on our CI to enable this registry.

**Comment by Zerpet** [comment]
Hey folks, I have manually pushed the latest version of the Cluster Operator to `quay.io`:

https://quay.io/repository/rabbitmqoperator/cluster-operator?tab=tags

Our CI is almost ready to start publishing to this registry following releases. We will publish only GA images. Dev, alphas, or other pre-releases will continue to live in DockerHub.

Hope this helps!

**Comment by philipp-hb** [comment]
cool, thx

**Comment by Zerpet** [comment]
Closing this issue, as we are publishing the images to quay.io and publishing a YAML manifest to our releases to deploy using the image from quay.io registry, [starting from 1.12.0](https://github.com/rabbitmq/cluster-operator/releases/tag/v1.12.0) and onwards.

P.s: I noticed the double extension in the file name. Future releases won't have that problem 🙂
