### ISSUE TITLE
Add enablefd flag for persistence

### ISSUE THREAD

**Issue by wirwolf** [rabbitmq/cluster-operator#871]
**Is your feature request related to a problem? Please describe.**
In my cluster, I don't have any storage classes.

**Describe the solution you'd like**
Add ```enabled:false``` in persistence block of CRD

**Describe alternatives you've considered**
Deploy as helm chart

**Comment by mkuratczyk** [comment]
If you mean you'd like to deploy RabbitMQ without persistent storage whatsoever (common CI/CD scenario), starting with the Operator 1.8.3, you can set `spec.persistence.storage` to `0` and the PVC will not be created.

**Comment by wirwolf** [comment]
@mkuratczyk not working. I deploy latest operator(1.10.0), and when I try to apply spec I see error in console 
```
error: error validating "rabbitmq.yaml": error validating data: ValidationError(RabbitmqCluster.spec.persistence): invalid type for com.rabbitmq.v1beta1.RabbitmqCluster.spec.persistence: got "integer", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```
