### ISSUE TITLE
`rabbitmq-upgrade post_upgrade` should be called after a rolling cluster restart

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#90]
RabbitMQ provides `rabbitmq-upgrade post_upgrade` command to run post-upgrade errands (currently it rebalances the queue masters). This command should be called whenever the operator triggers a rolling cluster restart.

Ideally, this command wouldn't be called by the operator explicitly but rather registered as a StatefulSet lifecycle hook so that it is executed always after a StatefulSet rollout restart, not only if the operator requested the restart.

**Comment by coro** [comment]
I investigated this today, and I believe I've found a hook we can rely on to get the behaviour we're after.

There are four operational events a cluster can go through, that may lead to a RabbitMQ user wanting to rebalance their system:

# Desired behavour

## Fresh Install / configuration update without node restarts

In the case where a StatefulSet has just been deployed for the first time, or where configuration has changed but the StatefulSet does not need a restart (e.g. enabling most plugins), either there are no queues to rebalance, or nothing has happened yet to cause the queues to be unbalanced.

In this case, we wish to call **nothing**.

## Rolling restart / configuration update with node restarts

In this case, the RabbitmqCluster CR has been configured with different properties as before. This will result in a new 'generation' of the StatefulSet being created, which can be observed in the Status of the object:

```
$ kubectl get sts sample-rabbitmq-server -ojsonpath='{.status}' | jq . 
{
"collisionCount": 0,
"currentReplicas": 2,
"currentRevision": "sample-rabbitmq-server-6fc5fff745",
"observedGeneration": 2,
"readyReplicas": 3,
"replicas": 3,
"updateRevision": "sample-rabbitmq-server-58f4db96c5"
}
```

In this case, there will be a rolling restart of the cluster, leading to an unbalanced distribution of leader nodes across the cluster. Note that `kubectl rollout restart sts <>` can be considered the exact same as a config change or upgrade in this case, as it functions by adding the `kubectl.kubernetes.io/restartedAt` annotation to the podSpec, and so will behave functionally the same as a config change.

In this case, we want to run the `rabbitmq-upgrade post_upgrade` command to rebalance the queues, as well as perform any other steps the command runs post upgrade.

N.B.: We may wish to split this, if the core team add behaviour to the post_upgrade script that would only be suitable for RabbitMQ server version upgrades. In this case, the ocntroller could inspect whether the image version has changed, and if so run post_upgrade, else just run `rabbitmq-queues rebalance`

## Pod restart

In the case where a Pod restarts in the StatefulSet, this does not trigger a new generation of the StatefulSet. This means that in these cases, the only command we need to run after it comes back up is `rabbitmq-queues rebalance`. We can wait for the `readyReplicas` to equal the `currentReplicas`, and once this is the case, run the command.

**Comment by mkuratczyk** [comment]
Great stuff! My only suggestion would be to call `rabbitmq-queues rebalance` rather than `post_upgrade` when the generation changes since that change tells us nothing about whether an upgrade took place. It feels more future-proof than calling a command that could gain "unwanted" (in no-upgrade scenario) functionality.

Calling `post_upgrade` when we know `image` property changed would be great as well.

**Comment by coro** [comment]
> Great stuff! My only suggestion would be to call `rabbitmq-queues rebalance` rather than `post_upgrade` when the generation changes since that change tells us nothing about whether an upgrade took place. It feels more future-proof than calling a command that could gain "unwanted" (in no-upgrade scenario) functionality.
> 
> Calling `post_upgrade` when we know `image` property changed would be great as well.

@mkuratczyk Happy to do this, though I don't see the difference between config changes & Rabbit version changes that would warrant differentiating between the two. Do you suspect that this command might be extended to something like database migrations, which wouldn't be appropriate for just config changes?

Also feel free to leave that feedback in the linked PR.

**Comment by mkuratczyk** [comment]
Yes, my point was that `post_upgrade` was specifically added as a command to combine post-upgrade errands in a single command and therefore might be extended in the future to perform actions that should not be performed unless there was an actual upgrade. I hope that such commands would be safe no-ops without an actual version change but if we had a guarantee that this would always be possible then this command would be called post_restart. :)
