### ISSUE TITLE
Guard rails around underprovisioned clusters

### ISSUE THREAD

**Issue by benmoss** [rabbitmq/cluster-operator#912]
**Is your feature request related to a problem? Please describe.**
[This](https://gist.github.com/benmoss/73ea68772a22fde0ec1c924f2ccb0a0b) is a completely valid RabbitMQCluster definition, but a user deploying it is pretty much guaranteed to run into memory alarms.

Is there something we can do around protecting/highlighting this problem from the vantage point of the cluster administrator?

**Describe the solution you'd like**
- Validating webhooks could define known minimum requirements for resources
- RMQ objects could have a status field that incorporates memory alarms
- RMQ objects could emit k8s events for memory alarms

**Comment by Zerpet** [comment]
This is a good initiative to ease the consumption of RabbitMQ cluster objects, however I prefer to implement the solution as at a different level than `RabbitmqCluster` object. 

We want to keep the `RabbitmqCluster` CRD with little to no-opinion on how users should configure their RabbitMQ clusters (part of the [motivation for STS and Service override](https://github.com/rabbitmq/cluster-operator/blob/main/docs/proposals/implemented/20200310-crd-spec-configurability.md#motivation)). With this in mind, I'd prefer to not implement restrictions in a validating webhook, but in a different CRD, or with some sort of templating with "safe" defaults.

The topic regarding exposing resource alarms via the status field and/or events is a bit more tricky than it seems. The main challenge is that RabbitMQ and the Operator live in different layers; basically, the Operator is not aware of everything that happens inside RabbitMQ, and RabbitMQ has no awareness of the Operator at all. This makes it challenging for the Operator to react to events happening inside RabbitMQ e.g. memory alarms, as there's no mechanism to trigger a reconcile loop when certain event happens inside RabbitMQ.
