### ISSUE TITLE
Publish operators on OperatorHub & OpenShift Community Operators

### ISSUE THREAD

**Issue by ctrought** [rabbitmq/cluster-operator#934]
**Describe the solution you'd like**
Please publish these operators in operator hub and and the openshift community operators repo to be deployed via OLM, this will make them available to users via https://operatorhub.io/ and the operatorhub catalogue integrated within OpenShift/OKD.

https://github.com/k8s-operatorhub/community-operators
https://github.com/redhat-openshift-ecosystem/community-operators-prod

Ideally both installation modes are supported (all namespaces, single namespace) which requires matching set of RBAC privileges and the operator to be able to handle the `WATCH_NAMESPACE` flag that OLM uses which gets set based on the installation mode.

https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#configuring-watch-namespaces-dynamically

Thanks!

**Comment by Zerpet** [comment]
Hey, I wanted to leave a comment to let you know that we are exploring this option, and what needs to be done our end to make it possible. Initial thoughts are "yes! we should do this"

**Comment by DanielePalaia** [comment]
Both cluster operator (v1.14.0) and messaging topology operator (v1.8.0) have been published on operatorhub:
https://operatorhub.io/operator/rabbitmq-cluster-operator
https://operatorhub.io/operator/rabbitmq-messaging-topology-operator
and redhat openshift community ecosystem:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1564
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1565

A github worfklow has been put in place also to automatize the publishing for the next releases.
In the next days we will also publish the single consumer operator.

**Comment by DanielePalaia** [comment]
Also the rabbitmq-single-active-consumer operator got published:
https://operatorhub.io/operator/rabbitmq-single-active-consumer-operator
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1574

I will close this ticket.
