### ISSUE TITLE
Investigating and bumps controller runtime and k8s api version

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#945]
**Is your feature request related to a problem? Please describe.**

Investigate what does it take to bump controller runtime and k8s api version to 1.23. If bumping to `1.23` does not does not introduce compatibility issue for k8s `1.19`, we can bump as part of this issue.

**Related PRs**
Cluster Operator:
https://github.com/rabbitmq/cluster-operator/pull/938
https://github.com/rabbitmq/cluster-operator/pull/925
https://github.com/rabbitmq/cluster-operator/pull/922

Messaging Topology Operator:
https://github.com/rabbitmq/messaging-topology-operator/pull/290
https://github.com/rabbitmq/messaging-topology-operator/pull/291
https://github.com/rabbitmq/messaging-topology-operator/pull/289
https://github.com/rabbitmq/messaging-topology-operator/pull/288
https://github.com/rabbitmq/messaging-topology-operator/pull/273

**Comment by ChunyiLyu** [comment]
Done as part of https://github.com/rabbitmq/cluster-operator/pull/965

**Comment by FischerLGLN** [comment]
@ChunyiLyu Hi, at Kubernetes 1.23.4 I noticed that it is required and best practice to prefix the docker hub image with docker.io/

This is the change for the two occurences of the image in the operator yaml:
```sh
image: rabbitmqoperator/cluster-operator:1.12.0
```
to this:
```sh
image: docker.io/rabbitmqoperator/cluster-operator:1.12.0
```
Could you change this please? :)

**Comment by Zerpet** [comment]
Thank you for bringing this to our attention! I created #991 to track that change.
