### ISSUE TITLE
How to reset the operator installation after corruption

### ISSUE THREAD

**Issue by marcelloraffaele** [rabbitmq/cluster-operator#946]
Hi Team,
I would ask if there's a way to force the reset of a corrupted rabbitmq operator.
We were receiving the following problem:
```
Warning FailedMount 10m (x537 over 18h) kubelet MountVolume.SetUp failed for volume "rabbitmq-cluster-operator-token-cvr7m" : failed to sync secret cache: timed out waiting for the condition
Warning FailedMount 36s (x483 over 18h) kubelet Unable to attach or mount volumes: unmounted volumes=[rabbitmq-cluster-operator-token-cvr7m], unattached volumes=[rabbitmq-cluster-operator-token-cvr7m]: timed out waiting for the condition
```

But when we decided to reinstall the operator but we didn't have success. The namespace `rabbitmq-system` remains in `terminating `state and if we force the deletion, the installation doesn't work. It seems that some old resource is blocking the installation.
Is there a way to clean up the resources and reinstall it from the beginning?

Thank you,
Raffaele

**Comment by Zerpet** [comment]
I replied in #948. Let's keep the conversation in the discussion 🙏
