### ISSUE TITLE
additional configuration not working

### ISSUE THREAD

**Issue by vinu1421** [rabbitmq/cluster-operator#963]
I am trying to change the default user and password using like like 

  rabbitmq:
    additionalConfig: |
      default_user=admin
      default_pass=*****

This is how it is defined in the examples - https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/set-login-password-username/rabbitmq.yaml

But getting Login failed error

**Comment by mkuratczyk** [comment]
Hi. What operation do you perform that you are getting the authentication failure?
I've checked and in my tests:
* the credentials are set as expected
* I can log in using guest/guest using Management UI
* I can connect over AMQP using guest/guest
* I can't, however, use `rabbitmqadmin`

The problem with `rabbitmqadmin` is that it has its own config file which indeed contains the generated credentials, rather than your specified credentials. Is you problem specific to `rabbitmqadmin`?

**Comment by vinu1421** [comment]
@mkuratczyk 
I am not able to access the management URL with the default username and password.
Also when checking the secret could see that the operator is creating new credentials and not using the one specified in the additionalConfig.

**Comment by vinu1421** [comment]
@mkuratczyk ok, let me try the topology operator.

Thx

**Comment by vinu1421** [comment]
@mkuratczyk I have configured the topology operator. But now getting this error
```
Internal error occurred: failed calling webhook "vuser.kb.io": Post "https://webhook-service.test.svc:443/validate-rabbitmq-com-v1beta1-user?timeout=10s": context deadline exceeded
```

**Comment by mkuratczyk** [comment]
Is the topology operator working? Has it been running for more than a few minutes? I've seen situations where webhooks take a bit of time for Kubernetes to start working. If it keeps failing or the Topology Operator doesn't start correctly, please report an issue in its repo with the logs and `kubectl describe` details.

**Comment by vinu1421** [comment]
@mkuratczyk The topology operation is up and running. There are no errors

**Comment by vinu1421** [comment]
@mkuratczyk I could see that many others are facing similar kinds of issues

I have opened a new issue with topology operator - https://github.com/rabbitmq/messaging-topology-operator/issues/303

This is a similar one - https://github.com/rabbitmq/messaging-topology-operator/issues/297, but there is no reply.

**Comment by coro** [comment]
Looks like there is advice now posted in https://github.com/rabbitmq/messaging-topology-operator/issues/303, so I will close this issue.
