### ISSUE TITLE
Support of rabbitmq stream

### ISSUE THREAD

**Issue by skyrain** [rabbitmq/cluster-operator#976]
**Is your feature request related to a problem? Please describe.**
Currently, rabbitmq support rabbitmq streams as https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview. I would love to know does the operator support stream? If so any way to enable it?

**Comment by mkuratczyk** [comment]
Yes, just enable the plugin if you want to start a Stream Protocol listener. Here's an example of enabling a plugin: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/plugins, of course in your case the plugin is `rabbitmq_stream` as documented in https://rabbitmq.com/stream.html.
