### ISSUE TITLE
Deploy rabbitmq-cluster-operator, restart many times

### ISSUE THREAD

**Issue by evaxiang** [rabbitmq/cluster-operator#977]
Rabbitmq cluster operator often triggers restart. The exit code of describe is 1. The reason cannot be analyzed by querying logs and events.
Please help me
--------
deployment：

> apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmqclusters.rabbitmq.com
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: rabbitmqoperator/cluster-operator:1.11.0
        name: operator
        ports:
        - containerPort: 9782
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 200Mi
      serviceAccountName: rabbitmq-cluster-operator
      terminationGracePeriodSeconds: 10

-------
describe-pods：

> Name:         rabbitmq-cluster-operator-54697d649d-bftwq
Namespace:    ops
Priority:     0
Node:         eu-west-1.10.121.1.76/10.121.1.76
Start Time:   Thu, 20 Jan 2022 12:21:08 +0800
Labels:       app.kubernetes.io/component=rabbitmq-operator
              app.kubernetes.io/name=rabbitmq-cluster-operator
              app.kubernetes.io/part-of=rabbitmq
              pod-template-hash=54697d649d
Annotations:  kubernetes.io/psp: ack.privileged
Status:       Running
IP:           10.121.32.221
IPs:
  IP:           10.121.32.221
Controlled By:  ReplicaSet/rabbitmq-cluster-operator-54697d649d
Containers:
  operator:
    Container ID:  docker://6cbf5e5b7595572623e7cc75fcb051263e12252f86e8a6bfab632c2d8a09708d
    Image:         rabbitmqoperator/cluster-operator:1.11.0
    Image ID:      docker-pullable://rabbitmqoperator/cluster-operator@sha256:2292f5ebac8982c2b9d9d8b75f15a4eee6774807ae625d23d1a8f91d703f9032
    Port:          9782/TCP
    Host Port:     0/TCP
    Command:
      /manager
    State:          Running
      Started:      Sat, 26 Feb 2022 07:21:58 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 24 Feb 2022 15:41:03 +0800
      Finished:     Sat, 26 Feb 2022 07:21:57 +0800
    Ready:          True
    Restart Count:  87
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:     50m
      memory:  200Mi
    Environment:
      OPERATOR_NAMESPACE:  ops (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from rabbitmq-cluster-operator-token-flzg6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  rabbitmq-cluster-operator-token-flzg6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rabbitmq-cluster-operator-token-flzg6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by coro** [comment]
Hello @evaxiang, a few questions:

- Is there a reason you've decreased the requested CPU / memory resources for the operator deployment from 200m/500Mi?
- Do you see this with the latest version of the operator?
- What is the CPU/memory usage like for that Pod at the point where it errors?
- Am I right in understanding that there's nothing in the logs of the Operator Pod to say why there was an error?

**Comment by dominykasn** [comment]
Hi there, I am also experiencing the same issue, should I open a new issue/thread or can we continue in this one?

**Comment by Zerpet** [comment]
It'll be best if you open a new discussion here: https://github.com/rabbitmq/cluster-operator/discussions
